== What is Cardano     

Cardano is a third generation, proof-of-stake blockchain platform. It combines pioneering technologies to provide a more secure and scalable infrastructure for the development of decentralized applications (DApps) and smart contracts. The project aims to address the shortcomings of existing blockchain platforms by focusing on _scalability_, _interoperability_, and _sustainability_. As a fully decentralized blockchain, Cardano can support a wide range of applications, from financial services to supply chain management, and beyond. 

=== Who built Cardano? ===
Cardano was founded on peer-reviewed research and developed through evidence-based methods. It was built by scientists, developers, and the extended team at https://iohk.io/[Input Output Global (IOG)], led by https://iohk.io/en/leadership/charles-hoskinson[Charles Hoskinson]. 

IOG (initially, IOHK) is a pre-eminent blockchain infrastructure research and engineering company with over 600 employees globally. This extends to a focused innovation ecosystem.

The Cardano project was launched in 2017 and is jointly supported by IOG, the https://cardanofoundation.org/[Cardano Foundation], https://emurgo.io/[Emurgo], and other third parties. It is named after https://www.britannica.com/biography/Girolamo-Cardano[Girolamo Cardano], the 16th century Italian physician and mathematician and its native cryptocurrency is ada, inspired by https://www.britannica.com/biography/Ada-Lovelace[Ada Lovelace], the 19th century English mathematician and programmer.

=== Mission ===
The core mission of Cardano, as a fully decentralized platform, is to improve the systems of the world to enable economic inclusion and empowerment for all. 

_“Cardano is an open platform that seeks to provide economic identity to the billions who lack it by providing decentralized applications to manage identity, value and governance”  (Charles Hoskinson, 2020)._

=== Open Source Ethos ===
Cardano is a thriving open source project with a healthy and vibrant ecosystem of active developers and builders. Open source principles are integral to Cardano’s identity as a decentralized blockchain platform. Collaboration and transparency with the Cardano community results in a robust and inclusive ecosystem that empowers users and developers alike. 

All of the research and technical specifications that underpin Cardano are publicly available, the codebase is open, and all Cardano development activity is published online.

=== Decentralization ===
Cardano is a fully decentralized blockchain. Let's take a closer look at what this means.

Cardano is maintained by almost 3,000 distributed stake pools that are operated by the community, making it fully decentralized. All blocks and transactions are validated by network participants without any reliance on a centralized authority. Decisions and ownership of information is shared amongst all users. 

Every ada holder also holds a stake in the Cardano network. Ada stored in a wallet can be delegated to a stake pool to earn rewards – to participate in the successful running of the network – or pledged to a stake pool to increase the pool’s likelihood of receiving rewards. In time, ada will also be usable for a variety of applications and services on the Cardano platform.

=== Proof of Stake ===
Cardano uses proof-of-stake to reach consensus. Fundamentally, Cardano has been built as a resilient and sustainable blockchain with a proof-of-stake consensus protocol called Ouroboros which is proven to have the same security guarantees as proof-of-work protocols and is undoubtedly more energy efficient. To learn more about Ouroboros, read the <x ref to Ouroboros chapter>.

Cardano builds upon Bitcoin’s UTXO model and implements an extended UTXO (EUTXO) accounting model that supports smart contracts. To learn more about EUTXO, read the <ETXO chapter x-ref>.

One of the features of Cardano is seamless upgrades. Traditionally, blockchains upgrade using hard forks. When conducting a hard fork, the current protocol would stop operating, new rules and changes would be implemented, and the chain would restart – with its previous history being erased. Cardano handles hard forks differently. Instead of implementing radical changes, the Cardano hard-fork combinator technology ensures a smooth transition to a new protocol while saving the history of the previous blocks and not causing any disruptions for end users.

=== Core Pillars of Cardano
As a third-generation blockchain, Cardano combines the properties of previous generations like Bitcoin and Ethereum and has been built as a resilient and sustainable platform using the core principles of security, scalability, and interoperability.

Let’s learn more about these core pillars of Cardano.

==== Security
Cardano has been built using formal methods which guarantees the functional correctness of core components of the system. These formal methods, such as mathematical specifications, property-based tests, and proofs, are the best way to deliver high-assurance software systems and give confidence to users in the management of their digital funds. 

Cardano is mostly written in Haskell, a secure functional programming language that encourages building a system using pure functions, which leads to a design where components are conveniently testable in isolation. Furthermore, the advanced features of Haskell enable us to employ a whole range of powerful methods for ensuring correctness of the code, such as basing the implementation on formal and executable specifications, extensive property-based testing, and running tests in simulation.

Ouroboros (the Cardano proof-of-stake protocol) establishes rigorous security guarantees; it was delivered with several peer-reviewed papers presented in top-tier conferences and publications in the area of cybersecurity and cryptography.

All of the research and technical specifications that underpin Cardano are publicly available, and all Cardano development activity is published online.

==== Scalability
The Cardano network is capable of processing an increasing number of transactions as user demand grows. Scalability also provides higher bandwidth capabilities to allow transactions to carry a significant amount of supportive data that can be easily managed within the network. For these needs, Cardano is implementing various techniques (like data compression for instance) and is working to introduce Hydra, which will enable multiple state channels functionality.

==== Interoperability
The ability to interact with other systems, or interoperability, is a fundamental design feature of Cardano. One of the current design innovations in Cardano is the use of sidechains, which means that you can compartmentalize the system and enable interoperability within the blockchain platform. Data can be kept off the main chain in what is called a sidechain. Multiple side chains can run concurrently, so if one part fails, the rest of the system does not fail, as it is maintained separately. This results in greater assurance and reliability within the blockchain. By using sidechains you can transfer assets between parallel blockchains that operate in different rules, mechanisms, or languages and ways of utilizing the network.

Cardano is also being developed to support cross-chain transfers, multiple token types, and commonly used smart contracts languages.

=== Sustainability and Governance
Governance is also central to the design of Cardano to ensure system sustainability and adaptability. A well-developed governance strategy will enable effective, democratic funding for Cardano’s long-term development. 

One of the key pillars for Cardano's viability is active community engagement and participation. This necessitates an effective governance mechanism. Using an iterative, anti-fragile approach and setting high standards for effective decision making, IOG provides the Cardano community with the mechanisms and human-processes required to help decide & build the future of Cardano. IOG plans to deliver this through absolute Liquid democracy - collective decision-making through direct participation and dynamic representation.

Designing a proof-of-stake blockchain means it is vital to ensure that the system is self-sustainable. To drive growth and maturity in a truly decentralized manner, Cardano is built to allow the community to maintain its continuous development by participating, proposing, and implementing system improvements. To ensure sustainability, the treasury system is controlled by the community and is refilled constantly from potential sources such as newly-minted coins being held back as funding, a percentage of stake pool rewards, and transaction fees.. In addition, Cardano Improvement Proposals (CIPs), will also be delivered to foster and formalize discussions around new features and their development within the community.

Central to the treasury is a democratized voting mechanism where ada holders will themselves decide how funds are allocated by voting on funding proposals. This will ensure that decisions are made by a democratic vote rather than by just a handful of stakeholders. This voting system will influence decisions such as funding initiatives, authorizing updates to the protocol, and rolling out any constitutional updates such as changes to the decision-making process, or the minting of new tokens.

Launched in 2023, https://www.intersectmbo.org/[Intersect] is a member-based organization for the Cardano ecosystem and puts the community at the core of Cardano’s future development. Bringing members together behind a shared vision, Intersect enables a more resilient, secure, transparent, and innovative Cardano ecosystem that puts members in the driving seat of Cardano’s future.

=== Cardano Roadmap ===
The https://roadmap.cardano.org/en/[Cardano roadmap] includes the following five eras:

- Byron — foundation establishment
- Shelley — decentralization
- Goguen — smart contracts
- Basho — scalability
- Voltaire — governance

Each era is centered around a set of feature that are being delivered across multiple code releases. While these development eras are delivered sequentially, the work for each happens in parallel – with research, prototyping, and development often in progress all at once across the different stages.

=== Suggested Reading
- https://www.essentialcardano.io/glossary/cardano-roadmap[Cardano Roadmap]
- https://docs.cardano.org/new-to-cardano/why-use-cardano[Why Use Cardano]


