== *Stake Pool Operator (SPO) Requirements*

Being that Cardano is an open protocol, and that cardano-node and cardano-cli are free and open-source software (FOSS), anyone is free to create and operate a stake pool. However, it is imperative that stake pool operators meet the level of technical expertise required to reliably and securely operate a pool on the Cardano network. While the requirements mentioned in this section are not authoritative, they are generally recognized as critical to stake pool operation.

It is also important to understand that many community-made tools and scripts exist that significantly lower the technical barrier to entry for stake pool operation. These tools exist to assist with tasks of operation and not to serve as a replacement for technical knowledge or ability.


==== *Linux*

A strong understanding of and ability to navigate, utilize and manage the Linux operating system is a must for any stake pool operator. For each release of cardano-node, binaries are made available for Linux, Mac and Windows but only Linux is supported in the block producer and relay roles. It is possible to build from source and operate cardano-node and cardano-cli on OpenBSD and potentially other unix-based operating systems, but that is an advanced and separate topic.

Suggested readings and courses:

* https://training.linuxfoundation.org/training/introduction-to-linux/[Introduction to Linux (LFS101x) by The Linux Foundation]
* https://ubuntu.com/tutorials/command-line-for-beginners#1-overview[The Linux command line for beginners Tutorial by Canonical]


==== *Networking*

A firm grasp of the Transmission Control Protocol and Internet Protocols (TCP/IP) and experience in working with and maintaining networks and interconnected devices as well as the protocols they connect with is crucial for SPOs as stewards of a large and distributed network. 

Suggested readings and courses:

* https://www.penguintutor.com/linux/basic-network-reference[TCP/IP Networking reference guide by Penguin Tutor]
* https://www.comptia.org/certifications/network[CompTIA Network + Certification]
* http://www.tcpipguide.com/[The TCP/IP Guide]

==== *Reading Documentation and Learning*

SPOs are required to not only keep nodes up-to-date, but to keep themselves up-to-date and informed as new node versions are released and on-chain changes are proposed and introduced with new node versions.

The Cardano node source-code is open-source, meaning that it can be looked at, cloned, forked, compiled and improved by the community and SPOs. Cardano’s code is currently released on Github.com, although it could be released on any version control platform. An SPO should be able to look at a project on Github such as Cardano, read through documentation, understand and follow along well enough to compile and run the node. 

Suggested reading:

* https://developers.cardano.org/docs/get-started/installing-cardano-node/[Cardano.org guide for installing Cardano node]

==== *Getting Started*

Prospective SPOs, both system administration newbies and veterans alike, should absolutely get started by using Cardano on public testnets. The Preview and Pre-production testnets are the two public testnets currently supported by IOG (there are other public and open testnets such as the https://github.com/cardano-community/guild-operators[Guild Network] that can be freely joined and used as well). The intended use of the Preview Testnet is for developers and users to test and provide feedback before things are released on mainnet and leads mainnet forks by 4 epochs by practice. The Pre-Production Testnet is used primarily by SPOs and developers to test major upgrades and releases before released on mainnet. The Pre-Production Testnet typically forks a single epoch ahead of mainnet. 

When someone considers launching a stakepool, it can be tempting to just download and run some of the fantastic scripts and tools put together by the community to help with the day-to-day operations of a pool. However, these tools were developed with the intent of making life easier for those that already know what they are doing. 

Instead of taking the easy path in the beginning and rushing directly to mainnet operation, it is strongly suggested that SPOs take time to learn how to do things by hand on one of the existing testnets. These tasks will include things like creating keys, compiling the node and CLI, crafting transactions and registering signed certificates to the blockchain. Time spent doing this will help reduce time and stress when problems arise during stake pool operations.

Here are a few useful guides and courses for setting up a stake pool:

* https://docs.cardano.org/development-guidelines/operating-a-stake-pool/creating-a-stake-pool/[Cardano Docs: Creating a stake pool]
* https://cardano-course.gitbook.io/cardano-course/handbook[Cardano Course: Handbook]
* https://developers.cardano.org/docs/operate-a-stake-pool/[Cardano Developer Portal: Operate a Stake Pool]
* https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node[Concashew’s Stake Pool Guide]

*Please note:* The recommended readings and courses shared in this section are not endorsements but rather suggested potential starting points for those interested in learning more and gaining experience in operations relative to stake pool operation.

==== *Putting it all together, long time maintenance*

Due of the stability of the Haskell-node, basic node operation is not quite the challenge it was in the early days of the Incentivized Testnet (ITN), especially when the current node is paired with community tools mentioned in "Getting Started" like https://cardano-community.github.io/guild-operators/[CNTools], https://bitbucket.org/muamw10/jormanager/src/develop/[JorManager], https://github.com/gitmachtl/scripts[StakePool Operator Scripts], or others not listed. 

Listed below are some things prospective SPOs should consider mastering or getting a firm grasp of before operating on mainnet in a professional manner. 

* Monitor node health and configure alerting for when something goes wrong such as missed blocks, node crashes, stuck block height, etc.
* Read and interpret logs from cardano-node to troubleshoot and find potential issues. 
  Investigate each missed block and determine what went wrong. Long-term luck should be near 100% and while block collisions that occur when the same slot is assigned to more than one pool happen, they are uncommon. More on this subject can be found in the https://github.com/input-output-hk/mastering-cardano/blob/main/chapters/chapter-stake-pools-and-stake-pool-operation/making_blocks.adoc[Slot Battles, Height Battles, Forkers and Propagation] chapter. 
* Help other SPOs analyze, contribute, and create cardano-node Github issues on the testnets or mainnet.
* Perform pool maintenance such as node or infrastructure updates without any service interruption.
* https://github.com/input-output-hk/mastering-cardano/blob/main/chapters/chapter-stake-pools-and-stake-pool-operation/server_security_and_hardening.adoc[Harden the pool environment.]
* https://github.com/input-output-hk/mastering-cardano/blob/main/chapters/chapter-stake-pools-and-stake-pool-operation/timesync.adoc[Keep the node and server synced to universal time.]
* Perform pool-relevant tasks such like pool registration updates without exposing keys.
* Expand resource provisioning for cardano-node without service interruption.
* Plan and configure failover for critical node failure.
