Ouroboros is the name of the protocol that runs Cardano, represented by the timeless symbol of the serpent eating its own tail. Until https://eprint.iacr.org/2019/838.pdf[Ouroboros Chronos] implementation is here however, the timeless Ouroboros needs stake pool operators to help it keep track of time.

Clock synchronization is typically essential in distributed networks. Nodes must avoid clock drift caused by counting time at slightly different rates from eachother. In Ubuntu or other Linux distros, a plethora of Network Time Protocol (NTP) programs exist to help reduce timesync offsets to the order of a few milliseconds. A commonly used program for this is Chrony which needs to be installed and running on the computer used as a node or relay for Cardano. On Ubuntu, Chrony can be installed with `apt install chrony`.

After installing Chrony, it is recommended to configure (default config file /etc/chrony/chrony.conf) with nearby high-performant NTP servers and poll them fairly often to reduce drift from the global clock. NTP categorizes sources into stratums. In general, stratum 0 is reserved for atomic clocks or other highly accurate time measurements. Stratum 1 is useful for systems allowed to deviate within a few milliseconds from stratum 0, and so on as stratum is increased. Stratum may be checked with the `chrony ntpdata`command. The following is an example chrony.conf configuration: 

[source, chrony.conf]
----
pool 192.168.2.100 minpoll 1 maxpoll 2 maxsources 1
pool time.cloudflare.com minpoll 3 maxpoll 4 maxsources 1
pool time.google.com minpoll 3 maxpoll 4 maxsources 1
maxupdateskew 5.0
makestep 0.1 -1
rtsync
leapsectz right/UTC
----
==== Comments on the example configuration :
* To add NTP servers add the pool with IP (such as 192.168.2.100) or DNS (such as time.google.com). 
* A low minpoll and maxpoll value means less time drift. Maxsources sets maximum sources from the pool. 
* Publicly available timesync servers from some of the larger corporations are fairly reliable and high performant such as time.cloudflare.com, time.google.com or time.facebook.com. The https://www.ntppool.org/en/[NTP pool project] also has an overview of NTP time pools all across the globe. Finally, running a local timesync server is another option to encourage decentralization. https://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html[Guides exist] for those that would like to build one using a Raspberry Pi.

* In the example configuration, a local Stratum 1 GPS across LAN (192.168.2.100) is used with a fast polling rate, as well as 2 public NTP servers (stratum 3 Cloudflare and stratum 1 Google) with a slower polling rate. An overly-aggressive polling rate may result in blacklisting by public timesync servers. 

* On modern fiber connections near the timesync server, a low acceptable value for Chrony’s internal estimate on how fast or slow the computer clock runs relative to the timesync server with maxupdateskew 5.0 (down from a default skew of 1000 ppm) is recommended.

* Chrony can adjust system clocks more often than default by setting a low makestep value such as makestep 0.1 -1 meaning adjusting for a drift of 0.1 at any time such a drift occurs. NICs with an internal clock for timestamps (can be discovered using ethtool -T) may also be enabled with hwtimestamp and the interface name or * for all interfaces. 

* Drift may be checked with `chronyc tracking` and `chronyc sourcestats` to view offsets and skew. 

* Rtsync can be set to enable the kernel to periodically copy the real time clock (every 11 minutes on Linux). In case the connected timesync server does not send leap seconds in advance, it may also be set with leapsectz right/UTC. In general, it is recommended to use Coordinated Universal Time for server time as this is the established common time standard, as most GPS based timesync servers report in UTC. 

With that out of the way in a fairly short time (pun intended) a stakepool operator will be able to keep Cardano nodes collaborating well with the rest of the network in a timely manner!
