:imagesdir: ../../images

[[FormalMethodsAndTheImportanceOfProgramCorrectness]]
=== Métodos formales y la importancia de la exactitud de los programas para los libros mayores de criptomonedas

Garantizar el comportamiento correcto de los libros mayores de criptomonedas(((libros mayores de criptomonedas))) implementados en
la tecnología blockchain(((tecnología blockchain))) conlleva un conjunto único de desafíos. Uno de los desafíos más importantes se deriva del hecho de que dichos programas son distribuidos,
lo que significa que los usuarios que ejecutan el código que participa en la implementación
de su comportamiento pueden tener incentivos contradictorios, y la red a través de
la cual se comunican puede ser impredecible. Probar las aplicaciones de blockchain
a escala presenta un serio desafío. Si se descubren problemas
después del lanzamiento, el proceso de corregir estos problemas en dicho
software puede ser muy lento y difícil, ya que puede ser imposible
dar de baja el código existente. Es particularmente complicado lidiar con
ataques informáticos del pasado provocados por vulnerabilidades existentes que pueden haber resultado en el robo de activos, o incluso paralizar por completo todo el sistema. Otra razón crítica para prestar especial atención a la exactitud de los programas para libros mayores de criptomonedas es, por supuesto, que los activos de los usuarios están en juego.

Las garantías de alta seguridad sobre el comportamiento de Cardano
deben incorporarse desde el principio y persistir a lo largo de su vida útil.
Los métodos formales(((métodos formales))) (MF) son técnicas matemáticamente rigurosas para asegurar la exactitud de programas(((exactitud de programas))) que pueden proporcionar tales garantías. Esta sección resumirá el impacto del uso de MF en el proceso de desarrollo de software, especificando cuándo es apropiado aplicarlos y las técnicas específicas de MF,
con un enfoque en su uso en Cardano.

==== ¿Qué son los métodos formales?

El enfoque de los métodos formales proporciona garantías sobre la exactitud del comportamiento
de un programa. Implica la aplicación de la lógica simbólica(((lógica simbólica))) para construir
especificaciones de comportamiento(((especificaciones de comportamiento))), definir sus propiedades, y luego verificar, probar o probar por propiedades (property-test) esas propiedades. Existen muchas técnicas diferentes de MF, y una variedad de herramientas.

Una especificación formal(((especificación formal))) es una descripción de lo que hace un programa dado (o un lenguaje de programación), es decir, su semántica, escrita en lógica simbólica y notación matemática. Puede consistir en una definición de cómo el
estado del programa (por ejemplo, el estado de un libro mayor o de un contrato inteligente) se actualiza en presencia de alguna entrada. En el caso de blockchain, dicha entrada puede ser
ticks de reloj, mensajes entrantes, bloques o transacciones. Para considerar un
ejemplo fuera de blockchain, un programa _contador_ puede tener un estado que es un
número natural, y para aplicar una solicitud de incremento entrante, el contador
se incrementa.

Una propiedad es una declaración sobre el comportamiento del programa, por ejemplo, 'cuando llegan dos solicitudes de incremento, el contador debe incrementarse dos veces'. Una
prueba es una evidencia lógica indiscutible de la verdad de una propiedad dada,
independientemente de todas las circunstancias externas. Siempre que estos formalismos
de lógica simbólica(((lógica simbólica))) (especificaciones, propiedades, pruebas, etc.) se programan y verifican usando software, son _mecanizados_.

==== ¿Qué nos aportan los métodos formales?

El uso de MF no garantiza una noción abstracta de 'la exactitud del programa(((exactitud de programas)))' de la implementación resultante. Más bien, aplicar
métodos formales significa responder a las siguientes preguntas para una pieza específica
de software que se está desarrollando, lo que ayuda a acercarse a una
implementación que tiene garantías de alta seguridad(((garantías de alta seguridad))) con respecto a ciertas propiedades de comportamiento:

[arabic]
. ¿Cuál es el alcance de la especificación?
. ¿Cuál es la especificación?
. ¿Cómo estar seguros de que nuestra especificación formal es realmente lo que queremos?
. ¿Cómo demostrar que la implementación también satisface esta especificación?

(1). Una especificación formal(((especificación formal))) rara vez modela la totalidad de la pieza de software que la implementará. Se pueden requerir múltiples especificaciones
para una pieza de software dada. Por ejemplo, Cardano tiene
especificaciones separadas para las capas de red, consenso, libro mayor y contratos
inteligentes. El alcance puede limitarse aún más omitiendo cierta
funcionalidad. Por ejemplo, la especificación del libro mayor puede dejar abstractos los
detalles del algoritmo de firma(((algoritmo de firma))), dando solo una API, o dejar
fuera por completo los detalles de la serialización de transacciones(((transacción, serialización))). Es esencial
ser claro sobre el alcance de lo que se está especificando. Un
alcance razonable es aquel en el que no hay efectos secundarios externos impredecibles,
restricciones o entradas que no se tengan en cuenta en la especificación.

(2). Un ingeniero de MF construye una especificación formal(((especificación formal))) pensando muy detenidamente en lo que quiere que haga el programa, a veces comenzando por
analizar una especificación informal(((especificación informal))) o una lista de requisitos. Por ejemplo, cuando se aplica una transacción al libro mayor, se verifica su validez.
La definición de la validez de la transacción(((transacción, validez))) debe darse mediante una especificación formal. Esto incluye detalles como '¿el intervalo de validez(((intervalo de validez))) `[a, b]` de una transacción incluye los puntos finales `a` o `b`?', o '¿necesita una
transacción especificar el conjunto exacto de claves que deben firmar para que
sea válida?'. No hay necesariamente una forma 'correcta' de completar estos
detalles – las decisiones deben ser tomadas por los ingenieros o las partes interesadas de una
manera que sea consistente y adecuada para los casos de uso relevantes.

(3). Las propiedades deseables de un programa se definen para especificar cómo se
espera que el programa se comporte en situaciones específicas. Estas propiedades
no son un resultado obvio de la especificación. Son el resultado de que
los ingenieros de MF piensen '¿qué queremos garantizar sobre el
comportamiento de este programa?'. Por ejemplo, 'el costo y el resultado de la
ejecución de un contrato inteligente son predecibles localmente' es una propiedad única y apreciada de la ejecución de contratos inteligentes de Cardano(((contrato inteligente, ejecución))), y no es necesariamente compartida por otras
blockchains. Al formular las propiedades deseadas del programa,
necesitan ser probadas o demostradas con un alto grado de
seguridad, si es posible. Si resulta que la especificación no satisface,
de hecho, la propiedad, pueden ser necesarios cambios en la especificación.

A pesar de que no es posible probar – o incluso enumerar – cada
una de las propiedades deseables del comportamiento de un programa dado, este
enfoque aporta muchas garantías importantes, además de ayudar a los
ingenieros a encontrar problemas en el proceso – generalmente mucho antes del despliegue.

(4). Una especificación se escribe comúnmente sin usar software, o con un
lenguaje de programación diferente al que se usa para escribir la implementación.
Siempre que una especificación se escribe como un documento de texto, un
humano debe verificar manualmente que la especificación y la implementación
coincidan. Cuando una especificación es mecanizada, puede ser posible
establecer pruebas de conformidad(((pruebas de conformidad))) entre ambas. Esto automatiza la
comparación entre las salidas de los programas de especificación e implementación
para un conjunto dado de estados y entradas, haciendo que las pruebas de conformidad sean muy útiles para mantener sincronizadas las dos bases de código.

==== Técnicas de MF utilizadas en la construcción de la plataforma Cardano

Para responder a cada una de las preguntas planteadas anteriormente, se aplican diferentes técnicas en Cardano ajustando el nivel de rigor formal a cada caso de uso particular.
La técnica de MF más prevalente dentro de Cardano es el uso de _sistemas de tipos_. Un sistema de tipos es un conjunto de reglas que asigna una propiedad simbólica de _tipo_ a cada término, por ejemplo, `5` es un `Integer`, `[1 ; 2]` es
una `List Integer`(((list integer))), `True` es un `Boolean`, etc. Un sistema de tipos puede proporcionar garantías como 'todos los elementos de esta lista son enteros', o 'no es
posible sumar un entero y un error'. Un sistema de tipos fuerte(((tipo))) puede
proporcionar garantías formales robustas, por lo que, citando a Simon Peyton Jones(((Peyton Jones, Simon))), los sistemas de tipos son 'el método formal más exitoso'.

Los sistemas de tipos fuertes son famosos por su ayuda en la refactorización de código. Esto
se debe a que cambiar el tipo de una variable o de la entrada o
salida de una función a menudo resulta en errores de compilación(((errores de compilación))) que incitarán al desarrollador a 'seguir los tipos', es decir, a refactorizar todas las partes relevantes del programa hasta que el sistema de tipos lo acepte. Esto a menudo coincide con
la finalización de la refactorización requerida. Por ejemplo, si un desarrollador
cambia la salida de alguna función para permitir que genere un error, todas las
funciones que la llaman también tendrán que ser refactorizadas para tener en cuenta
esta posibilidad adicional.

La _programación funcional_, aunque no es en sí misma un tipo de técnica de MF, es un
paradigma de programación(((paradigma de programación))) que facilita la escritura de programas que son altamente susceptibles a la especificación formal(((especificación formal))) y la verificación; son ampliamente utilizados en la tecnología central de Cardano. El nombre funcional se elige porque todos esos programas consisten en funciones, en el sentido matemático o lógico, es decir,

[source,shell]
----
    f : A -> B
    f (a) = …
----

donde el tipo de entrada es `A`, el tipo de salida(((tipo de salida))) es `B`, y `f` asocia a
cada término `a` de tipo `A` un término `b` de tipo `B`. Por ejemplo, si `A = B`, podemos
definir `f(a) = a`, la función identidad(((función identidad))). En programas funcionales _puros_, no hay estado subyacente o entrada adicional, como operaciones de entrada y salida (E/S) del usuario, o vinculaciones de variables(((vinculaciones de variables))), disponibles para `f` dentro del cómputo. Esto simplifica significativamente el razonamiento sobre las salidas de la función dada una cierta entrada (o conjunto de entradas).

Haskell es el lenguaje de programación elegido para construir el nodo
central de Cardano(((nodo de Cardano))), incluyendo los componentes de red, consenso y libro
mayor. Es funcional, tiene un sistema de tipado fuerte y ha existido
durante varias décadas, contando con una base de usuarios y mantenedores dedicada.
De hecho, antes de usar asistentes de prueba(((asistente de prueba))) para la especificación,
Haskell(((Haskell))) era el lenguaje para escribir tanto la especificación como la
implementación, siendo la diferencia entre ambos el nivel de optimización.

Las técnicas _semi-formales_, o no verificadas por máquina, también se utilizan para
construir Cardano, incluyendo especificaciones y pruebas en forma de documentos
de texto. Por ejemplo, para un estado UTXO(((UTXO, estado))) y una transacción dados, la
lógica simbólica puede expresar:

* Cómo el estado UTXO será actualizado por esta transacción, y
* Qué propiedades tiene una transacción válida.

Aunque hacer MF manualmente no es tan fiable como las técnicas
verificadas por máquina, este enfoque más ligero sigue siendo extremadamente útil.
Las eras de Cardano Shelley y Shelley con multi-activos(((era Shelley))) tuvieron
especificaciones de libro mayor escritas en este formato. Refactorizar tales especificaciones
para que coincidan con los cambios en la implementación es muy difícil, ya que se basa
en un análisis manual extremadamente cuidadoso en lugar de 'seguir los tipos'.

Los _asistentes de prueba_ son herramientas de software que asisten en el desarrollo
de pruebas y especificaciones formales. Un asistente de prueba(((asistente de prueba))) se compone de un entorno de desarrollo integrado (IDE) y un lenguaje de programación. Para
varios asistentes de prueba, el lenguaje de programación soportado es de tipado
dependiente, funcional y trata las proposiciones y el razonamiento lógico
como ciudadanos de primera clase. Soportan la construcción y prueba de
proposiciones, a veces también soportando cierto grado de automatización para
este propósito. Se pueden usar para proporcionar garantías más fuertes sobre el
comportamiento de un programa dado en comparación con los sistemas de tipos(((sistema de tipos))) que no soportan la construcción de pruebas. Lean, Agda, Coq e Isabelle(((Isabelle))) son todos asistentes de prueba utilizados para diferentes propósitos dentro de Cardano. La elección del asistente depende de una serie de factores, como la experiencia disponible
entre los ingenieros, la interoperabilidad con otros componentes del sistema y el
soporte para la automatización.

Por ejemplo, si comparamos una estructura de datos simple implementada tanto en Haskell
como en Agda, _set_ (conjunto) es una estructura de datos que contiene una colección de
elementos del mismo tipo, y cada elemento es único en esta colección. En Haskell, la unicidad de los elementos se asegura definiendo un procedimiento de inserción de un elemento `e` en un conjunto `S` que no hace nada cuando `e` ya está contenido en `S`, garantizando que no existan duplicados en la colección. Los desarrolladores entonces pueden confiar en el
hecho de que es suficientemente fácil definir la inserción correctamente o agregar algunos
casos de prueba. Un conjunto – como se define en Agda – es un par de (i) una
colección de elementos, y (ii) una prueba de que no hay duplicados en
esa colección. Esto hace imposible definir un mal procedimiento de inserción
que permita la duplicación accidental de elementos, lo cual es una
garantía más fuerte que la proporcionada por la implementación de Haskell.

Los asistentes de prueba(((asistente de prueba))) se han empleado exitosamente en la construcción de Cardano durante mucho tiempo para identificar problemas potenciales antes de que causen problemas en producción.
Por ejemplo, en el proceso de codificar la preservación del cálculo de
valor en un asistente de prueba, un ingeniero no pudo completar
la construcción de la prueba(((construcción de prueba))). El ingeniero se dio cuenta entonces de que se debía a una suposición incorrecta sobre ciertas funciones, y pudieron
corregir la especificación y la implementación en consecuencia.

Las garantías obtenidas a través de pruebas de software con técnicas tradicionales no son tan robustas como las _pruebas formales_ que ofrece el uso de la verificación formal(((verificación formal))). Sin embargo, los tipos especializados de pruebas son una parte integral de la aplicación efectiva de los Métodos Formales. El comportamiento de una especificación se define construyendo _propiedades_. Si hemos definido la especificación correctamente, estas propiedades serán verdaderas para cualquier ejecución del programa. El enfoque de usar un asistente de pruebas formales puede resultar demasiado riguroso para ciertas aplicaciones, es decir, demasiado difícil o que consume mucho tiempo. En su lugar, se utiliza un software especial llamado _generadores_, que sirve para producir un número extremadamente grande de trazas de ejecución válidas y aleatorias, y luego se verifica que la propiedad deseada se cumpla en las trazas generadas. Los generadores se ajustan para proporcionar una cobertura mejor y más realista. Este enfoque se denomina _pruebas de propiedades_.

Las _pruebas de conformidad_ son un tipo específico de pruebas de propiedades.
Proporcionan garantías de alta seguridad(((garantías de alta seguridad))) de que el comportamiento de la implementación para un estado y una entrada arbitrarios coincide con el comportamiento de la especificación para el mismo estado y entrada. Probar formalmente la
equivalencia entre la especificación y la implementación, especialmente cuando
la implementación está optimizada y escrita en un lenguaje diferente, es
bastante utópico. Las pruebas de conformidad son útiles para formalizar ciertos
aspectos de la equivalencia de comportamiento y proporcionar evidencia altamente fiable (si no
indiscutible) para respaldar estas afirmaciones.

Finalmente, se han desarrollado _modelos formales especializados_, como el
Desarrollo de Sistemas DELTA-Q, para simular el razonamiento sobre
sistemas reales antes de que se implementen y prueben. DELTA-Q permite el
modelado de rendimiento por adelantado. El análisis con esta herramienta se puede llevar a cabo antes de crear un prototipo para descartar la inviabilidad desde el principio y para dar
restricciones de rendimiento realistas. Por ejemplo, se ha utilizado para
excluir modelos que presuponen la existencia de conexiones de red transatlánticas
que son más rápidas que la velocidad de la luz.

En general, desarrollar nuevas herramientas, como la descrita anteriormente, así
como mejorar las existentes, es un componente importante de la
aplicación de métodos formales en Cardano, y en contextos industriales en general. Otros
ejemplos de trabajo de desarrollo de herramientas realizado como parte de la
ingeniería de Cardano incluyen contribuciones a las implementaciones de
Haskell(((Haskell))) y Agda(((Agda))).

==== Ajustando el nivel de formalidad

No todas las técnicas enumeradas anteriormente son adecuadas para todos los componentes de Cardano. La idea es ajustar el enfoque a cada componente y aplicar técnicas más
robustas con un mayor énfasis en la verificación a los componentes internos más
manejables, y aplicar un enfoque más ligero (seguridad de tipos, como
mínimo) con un mayor énfasis en probar los componentes externos impuros.

Las garantías formales más fuertes se pueden especificar y probar sobre el
_libro mayor_ y los _contratos inteligentes_ ejecutados en él. Esto se debe a que ambos
componentes están programados de manera pura. Además, estos
componentes están escritos de una manera que permite a los usuarios calcular localmente (es decir, antes del envío de un bloque o transacción) los cambios que provocará una transacción, o la salida de un contrato inteligente. Al igual que el componente del libro mayor(((componente del libro mayor))), la capa de consenso viene con ciertas propiedades formalmente probadas sobre su especificación. Sin embargo, al igual que el componente de red, también debe lidiar
con el cómputo concurrente(((cómputo concurrente))) y cierta imprevisibilidad, por lo que la
verificación formal no siempre es adecuada aquí.

La capa de red(((capa de red))) es un componente para el cual es más difícil
probar propiedades, ya que tiene que lidiar con la complejidad de la
comunicación no fiable. Por esta razón, en su lugar, se somete a intensas
pruebas basadas en propiedades(((pruebas basadas en propiedades))). Sin embargo, debido a que se apoya fuertemente en la concurrencia para operaciones eficientes, incluso las pruebas resultan desafiantes.
Se desarrollaron paquetes dedicados, incluyendo un mecanismo especial de control de concurrencia(((mecanismo de control de concurrencia))), para proporcionar una capa adicional de abstracción sobre partes del sistema de tiempo de ejecución de Haskell(((Haskell, sistema de tiempo de ejecución))) (RTS). El mismo código puede entonces ser ejecutado ya sea por el RTS de Haskell, o a través de una implementación pura y rápida que lo simula de forma determinista, permitiendo pruebas excelentes.

También se han desarrollado componentes adicionales fuera de la cadena(((componentes fuera de la cadena))) junto con Cardano, que tienen garantías formales, estadísticas y basadas en incentivos suficientemente robustas para que el sistema confíe en ellos en su operación.

==== Proceso de métodos formales y su impacto

Los métodos formales(((métodos formales))) establecen una conexión robusta entre la investigación y la implementación. Los artículos de investigación, junto con las implementaciones de prueba de concepto asociadas(((implementaciones de prueba de concepto))), a menudo son difíciles de transformar en implementaciones realistas y eficientes. Los MF facilitan este proceso al especificar exactamente lo que la implementación resultante tiene que hacer, mientras se mantiene el mismo nivel de rigor científico que en el trabajo de
investigación original. También hay algunas desventajas en el uso de MF, así que
listemos los pros y los contras de los métodos formales:

PROS:

* Proporcionan garantías muy sólidas sobre el comportamiento del programa, como la
ausencia (o una probabilidad muy baja) de ciertos tipos de errores en todas las
ejecuciones del programa
* Múltiples implementaciones construidas de acuerdo con un único modelo formal
tienen garantizada la misma funcionalidad.

CONTRAS:

* Requiere mucho tiempo, recursos, esfuerzo y experiencia
* Puede ser difícil de entender para los no expertos
* Las herramientas no siempre son fáciles de usar o están listas para producción
* Generalmente requiere que se realicen pruebas tradicionales junto con las pruebas formales
* Difícil de ajustar cuando ocurren actualizaciones de software (lo cuál puede considerarse como algo secundario).

Hay un tema común aquí – usar métodos formales es significativamente
más difícil en comparación con el control de calidad tradicional. Sin embargo, la
inversión de recursos (de tiempo, fondos, esfuerzo, etc.) en MF ha valido la pena para
Cardano, que ha estado funcionando sin tiempo de inactividad desde su lanzamiento en 2017, al menos hasta el momento de la publicación de este libro. Además, la tecnología central de Cardano
no ha sufrido ningún hackeo importante que resulte en el robo de
activos debido a problemas de implementación, y la rigurosa especificación formal(((especificación formal))) y verificación ciertamente merece crédito por esto.

La estrategia de MF del nodo de Cardano ha sido de gran ayuda para lograr la
tranquilidad que provee garantías sólidas sobre el comportamiento del programa.
Además, ayudó a establecer un lenguaje común para la comunicación
entre investigadores y profesionales, proporciona una forma de agregar
nuevas características basada en principios y proporciona un valioso material de referencia para
el desarrollo futuro.

La mayoría del trabajo de investigación e incluso la aplicación de métodos formales se realiza en un entorno académico. Hacer posible tal trabajo en un entorno industrial presenta algunos
desafíos, como se menciona anteriormente en la lista de CONTRAS. Para lograr un uso óptimo de MF
en Cardano, el trabajo de MF ha sido (i) mecanizado, por ejemplo, incluyendo
especificaciones en Agda y pruebas de conformidad(((pruebas de conformidad))), (ii) democratizado, es decir, hecho más accesible a una audiencia más amplia, incluyendo la comunidad de Cardano y los ingenieros internos, (iii) industrializado, es decir, tiene prácticas y estándares de desarrollo similares a los de la industria, y (iv) modificado para incluir un
alcance más amplio de aplicación de métodos formales, por ejemplo, la criptografía(((criptografía))).

Sin embargo, queda más trabajo por hacer en todas estas áreas. Una mayor
verificación de los protocolos criptográficos(((criptográficos, protocolos))) sería extremadamente valiosa.
Se está trabajando en la aplicación de métodos formales en áreas adicionales
del desarrollo de Cardano, incluyendo la certificación de compilación(((certificación de compilación))), la ejecución de código verificado en la cadena, y modelado adicional de rendimiento y seguridad. También se está trabajando más en la mejora de herramientas.
