== The (E)UTxO Model

Every cryptocurrency needs an _accounting model_ to keep track of who owns what.

One popular option for such a model is the so-called _account based_ model, where users have accounts storing their balances
and where transactions modify those balances.

Ethereum is one example of a cryptocurrency which uses the account based model.
If Alice and Bob initially hold 100 ETH and 50 ETH respectively
and if Alices sends 40 ETH to Bob, then their balances would be updated as follows:

[tikz,"image1",svg]
----
    \usetikzlibrary{calc}
    \begin{tikzpicture}[scale=1.8]

        \coordinate (a) at (5,5);
        \coordinate (b) at ($(a) + (10,-1)$);

        \node[draw, ultra thick, rectangle, fill=yellow] at (a)%
        {\begin{tabular}{lr}
            Alice & 100 ETH \\
            Bob & 50 ETH \\
            \ldots & \ldots \\
        \end{tabular}};

        \draw[->, ultra thick] ($(a) + (2,0)$) to[out=0, in=180] ($(b) + (-2,0)$);

        \node[above right] at ($(a)!0.5!(b)$) {Alice to Bob};
        \node[below left] at ($(a)!0.5!(b)$) {40~ETH};

        \node[draw, ultra thick, rectangle, fill=yellow] at (b)%
        {\begin{tabular}{lr}
            Alice & 60 ETH \\
            Bob & 90 ETH \\
            \ldots & \ldots \\
        \end{tabular}};

    \end{tikzpicture}
----

This model should be familiar to most readers with a bank account, because it is the model used by banks,
which reflects the way most of us tend to think about accounting.

The account based model is not the only model, though, and it is not the one used by Cardano.
Instead, Cardano follows Bitcoin in this regard and extends Bitcoin's _UTxO model_ to the so-called _Extended UTxO model (EUTxO)_.
