== Learn About Cardano

=== What is Cardano?
Cardano is an *open-source*, *proof of stake* blockchain platform. As a third-generation platform, it combines pioneering technologies to provide a more secure and scalable infrastructure for developing smart contracts and decentralized applications (DApps).

Cardano aims to address the shortcomings of existing blockchain platforms by focusing on security, scalability, and interoperability. As a fully https://informatics.ed.ac.uk/blockchain/edi[decentralized] blockchain, it can support a wide range of applications, from financial services to supply chain management and beyond. With the recent implementations of the https://iohk.io/en/blog/posts/2024/08/30/chang-upgrade-a-big-step-in-changing-the-world-with-cardano/[Chang] and https://www.intersectmbo.org/news/plomin-hard-fork-ratified[Plomin] hard forks, Cardano has become the most decentralized blockchain network in operation.

Cardano has a https://cardanoupdates.com/[thriving ecosystem] of builders, developers, content creators, and educators, as well as tools and explorers. There is a wide range of active projects and developer tools available to help you build on Cardano. If you would like to learn more about the vibrant Cardano ecosystem, see the https://www.cardanocube.com/cardano-ecosystem-interactive-map[ecosystem map], https://www.essentialcardano.io/[Essential Cardano website], and the https://github.com/IntersectMBO/essential-cardano[Essential Cardano list].

=== Who built Cardano?
The Cardano project began in 2015 and is based on *peer-reviewed research* and developed through *evidence-based methods*. It has been built by leading scientists, expert developers, and the extended team at https://iohk.io/[Input | Output (IO)] (initially IOHK), led by https://iohk.io/en/leadership/charles-hoskinson[Charles Hoskinson]. Input | Output is a pre-eminent blockchain infrastructure research and engineering company with over 600 employees globally. This extends to a focused innovation ecosystem.

The Cardano project is pioneered by https://iohk.io/[IO], the https://www.cardanofoundation.org/[Cardano Foundation], https://www.emurgo.io/[Emurgo], and other third parties. It is named after https://www.britannica.com/biography/Girolamo-Cardano[Girolamo Cardano], the 16th century Italian physician and mathematician and Cardano’s native cryptocurrency ada, is inspired by https://www.britannica.com/biography/Ada-Lovelace[Ada Lovelace], the 19th century English mathematician and the first person ever to publish a computer program.

Cardano follows an evidence-based engineering approach by applying formal logic to the software development cycle. This ensures that thoroughly researched and rigorous designs are turned into efficient implementations, guaranteeing correctness, safety, and code reliability. This process begins with published research papers which are later converted into formal specifications that evolve into reference implementations and products.

Prof Aggelos Kiayias, chief scientist at IO says:
_‘When you go about designing a system, you have to present the system in the context of the research domain in which it belongs, why the system has the benefits it claims to have, and what exactly is the problem that the system is solving. There are a lot of benefits in taking such a first principles approach.’_

=== Mission of Cardano
The core mission of Cardano, as a fully decentralized platform, is to improve the world’s systems to enable economic inclusion and empowerment for all.

Charles Hoskinson said in 2020:
_‘Cardano is an open platform that seeks to provide economic identity to the billions who lack it by providing decentralized applications to manage identity, value, and governance.’_

=== Open source ethos
Cardano is a thriving *open-source project* with a *healthy*, *vibrant ecosystem* of active developers and builders. Open-source principles are integral to Cardano’s identity as a decentralized blockchain platform. Collaboration and transparency with the Cardano community result in a robust and inclusive ecosystem that empowers users and developers alike.

All https://iohk.io/en/research/library/[research papers] and technical specifications that underpin Cardano, totaling over two hundred, are publicly available. The codebase is open, and all Cardano development activity is published online with weekly development updates for transparency.

=== Decentralization
Cardano is maintained by over 3,000 community-operated stake pools, ensuring full decentralization. Over 1.3 million wallets delegate to these stake pools,  representing approximately 64% of the total active ada supply. Network participants validate all blocks and transactions without any reliance on a centralized authority. Decisions and ownership of information are shared amongst all users.

Every ada holder also holds a stake in the Cardano network, ada stored in a wallet can be delegated to a stake pool to earn rewards and participate in the network’s successful operation. Stake pool operators can also pledge some ada to their stake pool to increase its likelihood of receiving rewards.

=== Reaching consensus using proof of stake
Cardano uses proof of stake to reach a consensus. Fundamentally, Cardano has been built as a resilient and sustainable blockchain with a proof-of-stake consensus protocol called https://iohk.io/en/blog/posts/2020/06/23/the-ouroboros-path-to-decentralization/[Ouroboros], which has been proven to have the same security guarantees as proof-of-work protocols and is undoubtedly more https://www.essentialcardano.io/article/comparison-of-energy-consumption-of-cardano-and-bitcoin[energy efficient]. To learn more about Ouroboros, read the <x ref to Ouroboros chapter>.

Cardano builds upon Bitcoin’s UTXO model and implements an extended UTXO (EUTXO) accounting model that supports smart contracts. To learn more about EUTXO, read the <ETXO chapter x-ref>.

One of the features of Cardano is seamless upgrades. Traditionally, blockchains upgrade using hard forks. When conducting a hard fork, the current protocol would stop operating, new rules and changes would be implemented, and the chain would restart. Cardano handles hard forks differently. Instead of implementing radical changes, the Cardano hard fork combinator technology ensures a smooth transition to a new protocol while saving the history of the previous blocks and not causing any disruptions for end users.

=== Core pillars of Cardano
As a third-generation blockchain, Cardano combines the properties of previous generations like Bitcoin and Ethereum. It has been built as a resilient and sustainable platform using the core principles of security, scalability, and interoperability.

Let’s learn more about these core pillars of Cardano.

==== Security
Cardano has been built using formal methods, which guarantees the functional correctness of its core components. These methods include producing mathematical specifications and proofs, which provide the highest level of assurance for software systems and give confidence to users managing their digital funds.

The Cardano node is primarily written in Haskell, a secure functional programming language that encourages building a system using pure functions. This leads to a design where components are conveniently testable in isolation. Furthermore, Haskell’s advanced features allow for a range of powerful methods for ensuring code correctness, such as implementing formal and executable specifications, extensive property-based testing, and running tests in simulation.

Ouroboros (the Cardano proof-of-stake protocol) establishes rigorous security guarantees. It was delivered with several peer-reviewed papers presented at top-tier conferences and publications in the area of cybersecurity and cryptography.
Scalability
The Cardano network is designed to scale as user demand grows, allowing it to process a growing number of transactions. Scalability enhances the network’s bandwidth,  enabling transactions to carry a significant amount of supportive data that can be efficiently managed. For these needs, Cardano employs various techniques like data compression and offers a layer 2 scalability solution – https://hydra.family/head-protocol/[Hydra].

Cardano also uses input endorsers to improve block propagation times and throughput. This improves the consistency of block propagation times and supports higher transaction rates.

==== Interoperability
Interoperability, the ability to interact with other systems, is a fundamental design feature of Cardano. One of Cardano’s key innovations is partner chain support, which enables the transfer of assets between parallel blockchains operating under different rules, mechanisms, languages, or network utilization methods.

Work is ongoing to support cross-chain transfers, multiple token types, and commonly used smart contract languages. The https://iohk.io/en/blog/posts/2024/08/01/announcing-the-alpha-v1-release-of-the-partner-chains-toolkit/[partner chains toolkit] marks the first step in this journey.

==== Sustainability and governance
Governance is central to the design of Cardano to ensure system sustainability and adaptability. A well-developed governance strategy enables effective, democratic funding for Cardano’s long-term development, promoting sustainability and organic growth in a decentralized manner. Decentralized governance and decision making are vital for providing everyone a voice and control over the protocol’s future development.

Charles Hoskinson says:
_‘Governance is not optional. No matter who you are, what you do, when you create something that other people use, the first question is how do we upgrade, maintain, and change it to meet our needs?’_

The community is central to Cardano's identity, and Cardano’s governance model reflects this by implementing liquid and representative democracy. Through individual participation and immutable vote recording, ada holders can decide on the distribution of treasury funds and the platform's future development. So, as a community, how can we work together to outline policies and guidelines for the future development of Cardano and ensure that everyone has a voice?

Designing a proof-of-stake blockchain means it is vital to ensure that the system is self-sustainable. Cardano Improvement Proposals (CIPs), are delivered to foster and formalize discussions around new features and their development within the community.

Cardano governance has a clear https://www.intersectmbo.org/roadmap[roadmap] guiding the community through the entire process. The stages of the Cardano governance roadmap, particularly under CIP-1694, reflect a structured approach to evolving Cardano's governance model into a decentralized, community-driven system. This roadmap facilitates a gradual transition, allowing for ample community feedback and refinement.

https://www.intersectmbo.org/news/cardano-cip-1694-explained[CIP-1694] was written by the community to discuss the future of on-chain governance for Cardano and ensure the platform's sustainability. Named after the birth year of Voltaire, this CIP aims to give everyone a voice and say in the direction of Cardano by advancing the current governance system. It outlines a voting framework to decide on updates to the protocol, new standards for on-chain improvements, funding decisions, and governance of Cardano native tokens. The proposal outlines a trilateral model consisting of stake pool operators (SPOs), delegate representatives (DReps), and a constitutional committee (CC), each with distinct responsibilities and roles.

Central to the treasury is a democratized voting mechanism where ada holders will decide how funds are allocated by voting on funding proposals. This approach ensures that decisions result from a democratic vote rather than from just a select group of stakeholders. This voting system will influence decisions such as funding initiatives, authorizing updates to the protocol, and rolling out any constitutional updates such as changes to the decision-making process, or the minting of new tokens.

Launched in 2023, https://www.intersectmbo.org/[Intersect] is a member-based organization for the Cardano ecosystem and puts the community at the core of Cardano’s future development. Bringing members together behind a shared vision, Intersect enables a more resilient, secure, transparent, and innovative Cardano ecosystem that puts members in the driving seat of Cardano’s future.

=== Design rationale of Cardano
Cardano, as a third-generation blockchain combines the properties of the prior generations and addresses previous limitations. It is the first blockchain platform to be designed from a scientific philosophy and research-first driven approach. Cardano is a decentralized and community-driven platform where the network is supported by an active community of global developers, researchers, and ada holders who contribute to its ongoing development and governance.

Cardano has been built in a way that ensures the highest security, scalability (transaction throughput, data scale, network bandwidth), and functionality (transaction processing and business deal settlement). Additionally, it is important to ensure that the technology was developed with the core tenets of transparency, sustainability and the ability to be interoperable with other blockchains and financial institutions.

Cardano has been designed with security as one of its founding principles. It is written in Haskell, the functional programming language. In a functional language like Haskell, building your system using pure functions is encouraged, which leads to a design where components are conveniently testable in isolation. Furthermore, advanced features of Haskell enable employing a whole range of powerful methods for ensuring the correctness of the code, such as basing the implementation on formal and executable specifications, extensive property-based testing, and running tests in simulation.

The design rationale of Cardano focuses on the following core concepts:

- Scalability – ensures that the Cardano network is capable of processing an increasing number of transactions as user demand grows. Scalability also provides higher bandwidth capabilities to allow transactions to carry a significant amount of supportive data that can be easily managed within the network. For these needs, Cardano is implementing various techniques (like data compression for instance), and introduces such scaling solutions as Hydra and Mithril, for example. Read more about the research underpinning Cardano's scalability here.

- Interoperability – ensures the most multi-functional environment for financial, business, or commercial operations by enabling users to interact with different blockchain systems. Cardano aims to support cross-chain transfers, multiple token types, and commonly used smart contract languages. Read more about the concept of partner chains.

- Sustainability – designing a proof-of-stake blockchain means it is vital to ensure that the system is self-sustainable. To drive growth and maturity in a truly decentralized manner, Cardano is built to allow the community to maintain its continuous development by participating, proposing, and implementing system improvements. This is now being implemented through CIP-1694 on-chain governance mechanisms.

==== Advantages​ of Cardano

- Academic research – formal methods, such as mathematical specifications, property-based tests, and proofs, are the best way to deliver high assurance software systems and give confidence to users for the management of digital funds. Cardano has been built using formal methods to achieve strong guarantees on the functional correctness of core components of the system. All of the research and technical specifications that underpin Cardano are publicly available, and all Cardano development activity is published online.

- System design – Cardano is written in Haskell, a secure functional programming language that encourages building a system using pure functions, which leads to a design where components are conveniently testable in isolation. Advanced features of Haskell enable employing a whole range of powerful methods for ensuring code correctness, such as basing the implementation on formal and executable specifications, extensive property-based testing, and running tests in simulation.

- Security – Ouroboros (the Cardano proof-of-stake protocol) establishes rigorous security guarantees; it was delivered with several peer-reviewed papers presented in top-tier conferences and publications in the area of cybersecurity and cryptography.

- Energy efficiency – Cardano is a proof-of-stake blockchain. In contrast to proof-of-work blockchains, Cardano requires much less energy and computational power. The Bitcoin network is secured through computers doing ever-more-energy-intensive computations – proof of work – which is unsustainable in the long term. Cambridge University has an online tool that shows the computers powering Bitcoin already consume more electricity than some countries, like Switzerland for example.

- Seamless upgrades – traditionally, blockchains upgrade using hard forks. When conducting a hard fork, the current protocol would stop operating, new rules and changes would be implemented, and the chain would restart – with its previous history being erased. Cardano handles hard forks differently. Instead of implementing radical changes, the Cardano hard fork combinator technology ensures a smooth transition to a new protocol while saving the history of the previous blocks and not causing any disruptions for end users.

- Decentralization – Cardano is maintained by over 3,000 distributed stake pools that are operated by the community. All blocks and transactions are validated by network participants without any reliance on a centralized authority.

- Functional environment for business use cases – Cardano is establishing a foundation for global, decentralized finance to develop a range of DApps that can run using functional and domain-specific smart contracts, providing multi-asset tokens for any needs.

=== Cardano community and growth of the ecosystem
Cardano benefits from a vibrant and thriving ecosystem that promotes active engagement with builders, developers, content creators, and users.The Cardano ecosystem is a dynamic and rapidly-growing collection of projects, organizations, creators, and builders who are working together to improve and develop the platform even further.

As a community-driven ecosystem, there is a strong focus on innovation, collaboration, and cooperation between innovators, smart contract developers, content creators, and distributed application (DApp) developers that build on Cardano. The aim is to grow the contributor ecosystem even more each year.

==== About the Cardano ecosystem
The Cardano ecosystem spans the globe with creators and builders dotted around the world. With many years of collaboration, innovation, and progress behind it, Cardano continues to grow and develop into a vast and self-governing ecosystem.

You can take a closer look at the vibrant landscape of Cardano’s ecosystem and explore the wide range of current projects using the Cardano Cube interactive map.

Another important resource is our community platform resource Essential Cardano. Here you can learn more about the growing Cardano ecosystem and keep up to date with regular development updates, blogs on various topics, and learning resources.

There are a number of builder tools and various community channels available within the ecosystem to help you navigate the environment, for example:
- https://developers.cardano.org/tools/[Builder Tools]
- https://www.essentialcardano.io/community[Cardano community channels]

==== Cardano improvement proposals
The https://cips.cardano.org/[Cardano improvement proposal] (CIP) process is a structured process that enables ideas for change and improvement within the ecosystem. It is a community-led mechanism that  provides transparency and encourages collaboration among stakeholders, thereby enabling the community to shape the future of the Cardano ecosystem together.

Anyone can write and submit a CIP, which typically covers both technical and non-technical suggestions and changes to Cardano. These CIPs must adhere to a set of guidelines and include a description of the issue, how it can be solved, and a plan on how to implement the changes. The next stage in the process is a review by https://cips.cardano.org/contributors[CIP editors] who ensure that it adheres to the set of guidelines, before they open it up for community discussion on whether or not it should be implemented. During this feedback cycle, the proposal is often refined and further improved, before it is moved to the implementation stage. In some cases, where there is a proposed protocol change, further governance is required by the founding entities.

Once a CIP is approved, it is implemented on-chain by the relevant developers and stake pool operators. In some cases, a network upgrade is needed which requires further collaboration between the various stakeholders. All CIPs are documented and maintained in the CIP repository, forming an audit trail of historical changes to Cardano.

==== Cardano Ambassador program
The https://cardano.org/ambassadors/[Cardano Ambassador program] promotes awareness, fosters relationships, and works to nurture and expand the wider community by increasing adoption. It includes a wide range of committed and hard working individuals from all around the globe with a wide variety of age and social profiles. These ambassadors work diligently as content creators, translators, moderators, and educators to strengthen relationships, educate, and bring more people into the growing Cardano community.

=== Educating the world about Cardano
Education is a gateway for adoption and has always been an integral part of the strategy of Cardano’s pioneering members: https://iohk.io/[Input | Output], the https://cardanofoundation.org/[Cardano Foundation], and https://www.emurgo.io/[Emurgo]. It plays a transformative role in fostering a knowledgeable and engaged global community by equipping them with the expertise, skills, confidence, and opportunities to deepen their understanding and successfully build on Cardano and thrive in the ecosystem.

Education is a gift that empowers and enhances Cardano community members through access to knowledge and experience so that they can overcome the complexity of blockchain technology. Pioneering worldwide education on blockchain offers the opportunity to shape the field for generations and leave a lasting legacy.

Whether you're a developer, an academic, or a business professional, Cardano’s educational offerings are designed to equip you with all the skills and knowledge you need.

You can read more about the education programs run by IO in the next section.

==== Input | Output education
The education team at IO brings together extensive experience in:

- Curriculum design and planning
- Project management and delivery
- Technical aspects related to blockchain
- Haskell and Cardano expertise
- Smart contract languages and development (including Plutus, Aiken, and Marlowe)

This collective expertise ensures that educational programs are both comprehensive and practical, tailored to meet the needs of diverse learners. The education team aims to enhance understanding of Cardano technologies using a variety of learning and training assets targeted at a wide range of audiences. The team aims to provide knowledge and information to enterprise decision-makers so they know what business problems the technologies can solve. It strives to create a supportive learning environment for all participants, and continuously shares what its team members have learned from working directly with our community members.

IOG is committed to improving the developer experience and smart contract adoption through education to further enhance the flourishing smart contract landscape on Cardano.
Partnerships
IO collaborates with esteemed universities and educational institutions worldwide to deliver high-quality education and is partnered with various universities and educational institutions, including:
University of Edinburgh, where there is a blockchain laboratory run by IOG’s chief scientist Prof Aggelos Kiayias and his research team
University of Athens
University of West Indies
University of Wyoming
Carnegie Mellon University
European Business University of Luxembourg
University of Malta
University of Wyoming
University of Cantabria

Additionally, IO worked with Yeovil College in the UK and Consilium Academy in South Africa on curriculum design for their blockchain programs.
Mission-based education
This education stream covers the Haskell training courses conducted over the years and aligns with the mission to provide free education to the Cardano community.

Haskell Course: aimed at those looking to master the functional programming language Haskell, which is integral to Cardano's development.
Cardano Days events: interactive events that provide a deep dive into the Cardano platform, covering its unique features and applications.
Blockchain workshops: in-person or virtual workshops and lectures on the fundamentals of blockchain and Cardano.
Essential Cardano: the Essential Cardano List repository was created in 2021 as a central canonical guide to the Cardano ecosystem. It serves as a resource for understanding Cardano,  identifying its partners, learning about its mission and roadmap, and getting started with building on Cardano. A new Essential Cardano website was launched in 2022 and has since become a thriving community resource.

As part of this stream, IO offers comprehensive in-person courses in Haskell that run for 10-12 weeks (depending on the curriculum). Dr. Lars Brünjes and his team have delivered several of these Haskell courses, including:

Haskell and cryptocurrency course 2017, which ran for eight weeks at the National Technical University of Athens.
Haskell and cryptocurrency course 2018, which ran for eight weeks at the University of West Indies, in Barbados.
Haskell course 2019 Ethiopia: this three-month course was delivered in Addis Ababa, Ethiopia, in conjunction with the Ethiopian Ministry of Innovation and Technology. It was delivered to an all-female audience of Ethiopian and Ugandan students.

Dr. Lars Brünjes says:

 ‘Education is a cornerstone of our approach at Cardano. By equipping individuals with the knowledge and skills to navigate and innovate within the blockchain ecosystem, we empower them to build a more decentralized and inclusive future. My greatest fulfillment came from teaching the all-female Haskell course in Ethiopia, witnessing firsthand the transformative power of education. That experience reaffirmed my belief in the potential of education to create substantive, lasting change.’


=== Suggested Reading
- https://docs.cardano.org/introduction/[Cardano Docs]
- https://iohk.io/en/blog/posts/page-1/[IO Blog]
- https://academy.cardanofoundation.org/[Cardano Academy]
- https://cardanofoundation.org/developer-portal[Cardano Developer Portal]
