== Introduction

The past years have seen many headlines touting how Blockchain, DLT, cryptocurrencies, smart contracts, NFTs, and DAOs (amongst others) will change society as we know it. Yet, to most people, what exactly these technologies are, what they mean to them, and how they will change society is unclear at best. Throughout this book we aim to both demystify what the technologies are but also provide readers with a starting point to developing such systems and decentralized applications (dApps). 

=== Where it all started, Bitcoin.

We start with the first proposal that sprouted this decentralized movement, Bitcoin, the first cryptocurrency. Bitcoin was proposed by Satoshi Nakamoto (who remains unknown to date) in a paper released in late 2008. The paper describes a novel (at the time) architecture built using a collection of techniques to solve the double spend problem -- a problem which had previously limited digital currency systems to those that required centralized servers or service providers. We now refer to systems that make use of these differet techniques as blockchain which is one type of distributed ledger technology (DLT).

Bitcoin's aim was to provide a digital currency system which did not rely on centralized service providers —- enabling individuals to send and receive digital currency without any intermediary, service provider, or authority who may be able to intervene or is required to approve transactions.

=== Blockchain and Smart Contracts

Blockchain, the collection of techniques that solve the double-spend problem, also provides a solution to creating digital systems that can execute code in a decentralized manner, where no single administrator, company, entity, owner, or other centralized party has control over the digital system upon which that code executes. Similar to how different software applications can be downloaded and run on computers to allow for computer to be used for many different things, code can be uploaded to a blockchain to allow for different uses of executing code in a decetralized manner. Code that is uploaded to a blockchain for decentralized execution are called smart contracts (we'll cover them in more detail later). 

Since smart contracts execute on a blockchain, this means that code can be executed in a manner that is tamper-proof and provides guarantees to all users that the system will do exactly what that code is written to do, without anyone having the ability to tamper with the system including its code and associated data. Given that developers can write code for different applicatios, smart contracts allow for blockchains to be used for so much more than just a means of sending and receiving digital currency, including the democratization of and access to financial services to anyone with an internet connected digital device (5 billion people at the time of writing), which includes over 600 million people that are unbanked. But it is not just about the democratization of financial services, other applications that have already been implemented and are being proposed include: decentralized property and land registries allowing for self-sovereign ownership -- ensuring that individuals do not lose their property just because a paper goes missing, or even if the land registry itself is destroyed; **supply chain; self-soveirgn identity; digital assets NFTs and digital games; transparency and open processes in government and other entities; **

Being decentralized, blockchain promotes openness and transparency, yet also privacy -- achieved through cryptography (which is a major building block of cryptocurrencies as the name implies). Personal details are not required for sending and receiving funds and neither to interact with other blockchain-based processes, while at the same time users can be validated, recorded, where required guarantees provided and logic based upon the interacting users executed — all of this whilst preserving privacy.

