= Developer Portal
Markus Gufler <m@rkus.it> 
:description: An introduction to the Cadano developer portal
:sectanchors: 
:url-repo: https://github.com/input-output-hk/mastering-cardano/new/main/chapters

==== Overview
https://developers.cardano.org/[The Developer Portal] is one of the cardano.org websites: a product-and-vendor neutral contact point for technical topics. 

With the spirit as a guiding principle to involve the community as much as possible, all content is entered openly and transparently via a git process (branch, pull-request, review, merge). This means that anyone can submit a proposal with new or updated markdown formatted content and thus contribute actively and constructively.

Under the hood, https://docusaurus.io/[Docusaurus] (an open source project for building, deploying and maintaining websites) works as a generator of web pages with extensive search functions. 

==== Content

Developer Portal content is intended to exemplify and practically demonstrate how certain functions and operations can be implemented on the Cardano Blockchain, as well as showcasing existing projects. A basic principle for the inclusion of projects requires a functioning and usable project on the mainnet. (see guideline for https://developers.cardano.org/docs/portal-contribute/#add-a-project-to-showcase[adding new projects])

The developer portal provides resources to https://developers.cardano.org/docs/integrate-cardano[integrate Cardano], https://developers.cardano.org/docs/transaction-metadata/[build with transaction metadata], https://developers.cardano.org/docs/native-tokens/[explore native tokens], https://developers.cardano.org/docs/smart-contracts/[create smart contracts], https://developers.cardano.org/docs/governance/[participate in governance], and https://developers.cardano.org/docs/operate-a-stake-pool/[operate a stake pool].

==== Contributors

In order to achieve constant evolution by the community, contributions from all individuals, including non-developers, are encouraged. Contributing to the portal can boost reputation and visibility, or serve as a good learning experience in the github open-source and knowledge-minded contribution process. Each contribution acts as a valuable addition to your resume, potentially leading to career opportunities within the Cardano ecosystem. Ways to contribute include spreading awareness, creating issues on GitHub or the Cardano Forum, improving texts by fixing errors or enhancing writing, and creating explanatory graphics.

There is even a dedicated section that describes https://developers.cardano.org/docs/portal-contribute[how best to contribute].

https://developers.cardano.org/tools[The Builder Tools] section of the developer portal encourages the addition of valuable tools that benefit Cardano developers. Guidelines for adding tools include being an actual builder tool, having a stable domain name, and using a GitHub account with a history or presence in the Cardano community. 

The documentation in the portal can be improved and users are encouraged to contribute by creating and enhancing tutorials. Reviewing pull requests is another way to contribute, requiring technical understanding and prior contributions. The FAQs cover topics such as pull request review process, becoming a reviewer, getting added to the contributor list, and connecting with the developer community through Discord and the forum.
