
[[foreword-joshua]]
== Prólogo de Joshua Ellul

Tuve el placer de conocer al Dr. Lars Brünjes (coautor de este libro y Director de Educación en Input | Output (IO)) en 2019. En ese momento, acababa de asumir el cargo de Director del Centro de Tecnologías de Registro Distribuido (*Centre for Distributed Ledger Technologies* (DLT)) de la Universidad de Malta y me encontraba enfocado en el desarrollo del plan y del programa de estudios de una maestría multidisciplinaria en Blockchain y DLT. No pude haber conocido a Lars en un momento más oportuno dado que deseaba asegurar que Cardano se incluyera en el curso de programación de contratos inteligentes (a fin de cubrir distintos paradigmas de programación de smart contracts) y, ¿quién mejor para abordarlo que alguien del propio ecosistema de Cardano? Exploramos diversas iniciativas de colaboración y, además de la participación de Lars en clases magistrales como profesor invitado, surgieron dos esfuerzos notables: (i) organizamos una edición de los talleres Cardano Days en la Universidad de Malta, donde tuvimos el honor de contar con el equipo de Educación de IO liderando el evento; y (ii) este libro, *Mastering Cardano*.

Gracias a mi participación en *Mastering Cardano*, he tenido la oportunidad de trabajar con un gran equipo y con una comunidad aún mayor. Este libro refleja el resultado de la colaboración entre académicos, profesionales y miembros de la comunidad Cardano. A medida que la plataforma evoluciona, también lo hacen el conocimiento y las mejores prácticas. Por ello, el aprendizaje y el desarrollo en el ecosistema Cardano son procesos continuos y, en consecuencia, este libro debe considerarse como propiedad de la comunidad, a quien animamos a involucrarse para mantenerlo vivo y en código abierto.

A lo largo del proceso de concepción, redacción y edición del libro, me quedó cada vez más claro que Cardano no es simplemente otra blockchain. Es una blockchain construida con la descentralización y la filosofía científica como principios rectores—y son precisamente estos principios los que han moldeado mi carrera durante la última década. Como alguien que ha trabajado en la intersección de la tecnología, la educación, las políticas públicas y la regulación (una combinación que, si se ejecuta correctamente, puede ser sumamente provechosa), considero a Cardano como algo más que una blockchain,lo veo como un experimento vivo de cómo una infraestructura digital crítica puede desarrollarse y gobernarse de manera responsable, y aplicarse de forma significativa a casos de uso del mundo real y a desafíos globales. Mi esperanza es que este libro no solo brinde a los lectores las herramientas para comenzar con Cardano, sino que también les permita apreciar por qué Cardano es diferente (y no simplemente otra blockchain).

Tanto si es nuevo en Cardano, como si es desarrollador, operador de stake pool, una persona interesada en la gobernanza de Cardano o lee este libro con otro propósito, lo invito a explorar lo que Cardano puede ofrecer para construir un futuro más abierto, responsable y descentralizado.

_Prof. Joshua Ellul +
Profesor Asociado +
Departamento de Ciencias de la Computación y Centro de Tecnologías de Registro Distribuido +
Universidad de Malta +
Malta +
Julio de 2025_
