
[[foreword-joshua]]
== Joshua Ellul序文

私が嬉しくも本書の共同著者でありInput | Output (IO)の教育ディレクターであるLars Brünjes博士の知己を得ることができたのは2019年のことでした。当時、マルタ大学DLTセンターのディレクターとしての役割を始めたばかりだった私は、ブロックチェーンとDLTの学際的な修士課程のプログラムとカリキュラム開発に注力していました。このLarsとの出会いは最高のタイミングでした。というのも、私はスマートコントラクトプログラミングコースで絶対にCardanoを採り上げたかったし（さまざまなスマートコントラクトのプログラミングパラダイムを網羅しようとしていたので）、それを扱うのにCardanoエコシステムのメンバーに勝る適任者はいないでしょう。私たちは共同で取り組むためのイニシアチブを模索しました。そして、Larsがゲスト講師として関わることに加えて、注目すべき2つの共同作業が生まれました。一つ目は、マルタ大学でCardano Daysワークショップを開催し、IOの教育チームにこのイベントを主導してもらうという栄誉を得ました。そして二つ目が、本書『Mastering Cardano』です。

私は『Mastering Cardano』に関わる中で、LarsやIO教育チームの他の人々と仕事をする機会と喜びを得ました。この経験を楽しみ以上のものにしてくれた、Alejandro Garcia、Jose Arturo Mora、Jesse Smith、Luka Kurnjek、Niamh Ahern、そしてCardano財団のJohn Greenの諸氏をはじめとする人々に、感謝の意を表します。実際、Larsが指摘したように、『Mastering Cardano』は、Cardanoエコシステムの発展と開発に伴い更新が必要な、生きている本であるべきです。したがって、本書は、この本を存続させ、オープンソースに保つことに取り組むコミュニティのものと見なされるべきです。

本書の草稿、執筆、編集を通して、私の中でCardanoは単なるブロックチェーンではないことがどんどん明確になっていきました。これは、分散性と科学哲学を基本原理として構築されたブロックチェーンであり、この10年間の私の業績を形作るのに役立ったのは、まさにこれらの原理です。技術、教育、政策、規制（これは、正しく行われれば有益だと私が信じるものです）が交差する場で働いてきた私は、Cardanoを単なるブロックチェーンではなく、重要なデジタルインフラがいかに責任を持って開発され、管理され、現実世界のアプリケーションやグローバルな課題に有意義に適用され得るかを知るための、生きた実験と見ています。私の望みは、この本が読者にCardanoを使い始めるだけでなく、Cardanoがなぜ違うのか（そして単なる別のブロックチェーンではないこと）を理解してもらうことです。

あなたがCardano初心者であっても、開発者であっても、ステークプールオペレーターであっても、Cardanoのガバナンスに興味がある方であっても、あるいは別の目的でこの本を読んでいる方であっても、私は、よりオープンで、説明責任があり、分散化された未来に向けてCardanoが提供するものを、ぜひ探求していただきたいと願っています。

_Joshua Ellul教授 +
准教授 +
マルタ大学コンピューターサイエンス学科およびDLTセンター +
マルタ +
2025年7月_
