== What is Cardano?

* Cardano explained - Niamh   
* Roles of IOG and the Cardano Foundation - JG    _...add to / edit extract from CFTM_
* Cardano Community and Growth of the Ecosystem - JG    _reference Essential Cardano, CardanoCube.io, etc_
* A Map of the Cardano Ecosystem - JG/Niamh    

   
== Roles of IOG, Emurgo and the Cardano Foundation

Cardano was designed by a global team of experts across multiple disciplines including distributed systems, programming languages and game theory. Cardano has traditionally been supported by three core entities: Input Output Global, the Cardano Foundation and EMURGO. 

Input Output Global (add logo)

Input Output Global, or IOG, is the engineering company originally tasked with building Cardano. Founded by Charles Hoskinson and Jeremy Wood as Input Output Hong Kong, or IOHK, the company was renamed IOG to reflect its global presence. IOG is committed to innovation through rigorous scientific peer review and the most stringent quality assurance standards in software development. IOG has several partnerships with leading universities to uphold the highest academic standards and to commit to a positive impact on the broader scientific community.

Cardano Foundation (add logo)

The Cardano Foundation is a Swiss-based independent standards body. Its responsibilities are overseeing and supervising the Cardano's development and its ecosystem. The Cardano Foundation focuses on three core areas: operational resilience, education and adoption. 

EMURGO (add logo)

EMURGO was entrusted with creating, fostering, and supporting Cardano's commercial potential. It facilitates the integration of businesses into Cardano and serves as the for-profit division of the network. Through commercial initiatives, EMURGO aims to enhance the platform and increase usage.

The voyage was began by these three entities. They now comprise the driving force that propels the Cardano blockchain forward along with the broader Cardano community.  

== Cardano Community and Growth of the Ecosystem

see https://www.cardanocube.io/cardano-ecosystem-interactive-map ..._and https://builtoncardano.com/ ...This is challenging to capture this in readable book format (one-pager) and likely to keep changing. Could link to it or perhaps have page for each category: DEXs, Wallets, etc

The ecosystem is covered in this report from Dec 2022 -- https://www.iogservices.io/guide-to-the-ecosystem-ty?submissionGuid=7ee23255-2361-418d-9d47-d0cd41703e2e

Suggestion: there are projects covering this on daily / weekly basis, CardanoWithPaul, CardanoOverCoffeee, + others. Also 'this week in cardano' with Sooraj, and 'cardano pills'...We can think of some way of capturing this, maybe a list in the book. 

