= `cardano-cli`

== Prologue

As its name suggests, the _Cardano command line interface_ (`cardano-cli` for short), is the low-level CLI (command line interface) component of the `cardano-node` repository. It is the perfect companion to the `cardano-node` and is often built alongside or provided as a pre-compiled binary together with `cardano-node`. What for? To simply interact with the blockchain being built in the background by `cardano-node`. Would you drive a car without a steering wheel?!

Here, we will focus on the subset of `cardano-cli` commands most useful to Cardano Stake Pool operators. This entire chapter contains the steps required to set up a stake pool from the very beginning. Namely:

* Key generation for addresses and pools
* Certificate generation
* Node queries
* Basic transaction

To walk through these, we will assume you have:

* `cardano-cli` installed in your machine.
* `cardano-node` installed in your machine, running and synced to a publicly available Cardano network (`preview`, `preprod` or `mainnet` for example).
* the `CARDANO_NODE_SOCKET_PATH` properly set in your environment so that `cardano-cli` knows how to talk to your running instance of `cardano-node`.
+
_Note that the last two points are only required when submitting a transaction or querying the ledger. In other words, a running node is handy when you need to interact with or access the current state of the blockchain. Generating keys, addresses or certificates only require `cardano-cli` and should sometimes be done entirely offline for security reasons!_

Before starting, let's check that both `cardano-node` and `cardano-cli` are up to date. Paste the following code snippet below in your terminal.

----
cardano-node version
----

Your terminal should reply something along those lines:

----
 cardano-node 1.35.6 - linux-x86_64 - ghc-8.10
 git rev 07b0c71d2e6662aec4389ec282a7e91f68c3d85f
----

Let's ask `cardano-cli`.

----
cardano-cli version
----

----
cardano-cli 1.35.6 - linux-x86_64 - ghc-8.10
git rev 07b0c71d2e6662aec4389ec282a7e91f68c3d85f
----

Same version (`1.35.6`), and better, both originate from the same code branch (`+git rev 07b0c7...3d85f+`). Perfect!

____
Notice how we access the `version` command of `cardano-cli` (or `cardano-node`): a single space character is used to navigate through the available commands and here, `version` takes no extra parameters. As you will see later, parameters are passed using a double hyphen (`--`).
____

== Keys generation

Public/private key pairs are everywhere in cryptography. In Cardano, the controller of a private key can spend ada contained in an address, sign a block or prove to other nodes they were meant to sign a specific block.

____
*All private keys should be sufficiently protected from both prying eyes and accidental deletions or squashings alike. Since the launch of Shelley, many examples of mismanaged keys exist leading to non-functional stake pools or in rare instances, stolen funds.*
____

=== Addresses

Every action recorded on the ledger will _a minima_ require a transaction fee. An address must pay for this transaction fee and/or provide funds as a deposit (cf. section _Basic transaction_). Here, let's describe how to generate address key pairs and derive a base address that will be used to create and register a stake pool. Note: This section is not a complete reference for `cardano-cli` relative to addresses.

==== Payment key pair

We will refer to this as the *`payment`* key pair. We will use the suffix *`vk`* to identify the *payment public key* (or verification key) and the suffix *`sk`* to identify the *payment private key* (or secret key). Remember that in Cardano, ada contained in an address is under the control of the `payment.sk` only.

Let's generate one.

----
cardano-cli address key-gen --verification-key-file ./payment.vk --signing-key-file ./payment.sk
----

As alluded to earlier, `address` and `key-gen` are two nested commands of `cardano-cli`, while `--verification-key-file` and `--signing-key-file` are parameters of the entire command.

In the directory where you executed the command, you should have the following files:

----
payment.sk
payment.vk
----

Both files have the structure shown below:

----
cat ./payment.vk
----

----
{
    "type": "PaymentVerificationKeyShelley_ed25519",
    "description": "Payment Verification Key",
    "cborHex": "5820205d42785c7dc9a46898655ecda8dad8b14e47747dc94ba184edc8ada0b72969"
}
----

The `payment.sk` has the same structure, with the type `PaymentSigningKeyShelley_ed25519` and of course a different `cborHex` value. You won't know more, it is a secret after all.

We now have what we need to derive an address to receive funds:

----
cardano-cli address build --payment-verification-key-file ./payment.vk --mainnet > payment.addr
----

The newly created `payment.addr` file contains an address in the format:

----
addr1v9m8pcfxszyvx7gytqc2s9l400aund8z7sazfs2jtfy4h3gnt67k6
----

Three things to note:

* `--payment-verification-key-file` is the sole parameter needed for payment address creation.
* We used the `--mainnet` parameter to create this address. It means that this address won't be of any use on a testnet. Conversely, the `--testnet-magic` parameter would allow us to create an address for a specified testnet. Mishaps avoided!
* Cardano Preview Testnet is on `--testnet-magic 2` and Cardano Preprod Testnet is  on `--testnet-magic 1`

==== Staking key pair

Using the address generated above has one big drawback... it can receive and send ada, but has no staking rights associated to it, making it what we call an `enterprise address`. Let's add those.

In the same folder where our payment key pair is located, let's generate a *`staking`* key pair. Following convention, we will call them *`stake.vk`* and *`stake.sk`*.

----
cardano-cli stake-address key-gen --verification-key-file ./stake.vk --signing-key-file ./stake.sk
----

Both files have the structure shown below:

----
{
    "type": "StakeVerificationKeyShelley_ed25519",
    "description": "Stake Verification Key",
    "cborHex": "5820eaa448543c3f95cbecf5c7ef00e481695388462c7e470b90052920138272a88b"
}
----

Similarly, we can build the corresponding staking address using the `stake.vk`.

----
cardano-cli stake-address build --stake-verification-key-file ./stake.vk --mainnet > stake.addr
----

The newly created `stake.addr` file contains:

----
stake1uy4hlpcmhd026m4ny9y9uxl94rez479g8h0sqalljf9zehguqnhcm
----

==== Building an address

As you have seen, the payment key pair and the staking key pair can both be used to generate addresses. While the payment address (or `enterprise address`) can be used to receive or send ada, that is not the case for the staking address. As such, a staking address is useless. It will only come to life when associated with ada residing within a payment address.

----
cardano-cli address build  --payment-verification-key-file ./payment.vk --stake-verification-key-file ./stake.vk --mainnet > base.addr
----

The newly created  `base.addr`  file contains an address that combines the best of both worlds, the ability:

1) To send and receive ada.
2) Delegate stake and perceive rewards for doing so.

----
addr1q9m8pcfxszyvx7gytqc2s9l400aund8z7sazfs2jtfy4h3ft07r3hw6744htxg2gtcd7t28j9tu2s0wlqpmllyj29nwssucyxn
----

Note that this address is longer than an `enterprise address`.

==== File Summary #1

Your working directory should now contain 7 files:

----
base.addr
payment.addr
payment.sk
payment.vk
stake.addr
stake.sk
stake.vk
----

It is now a good time to back up those key pairs and send some ada to the `base.addr` in order to fund our next venture: creating a stake pool.

=== Stake Pool related key pairs

The creation and operation of a Cardano stake pool relies on three public/private key pairs.

==== Stake Pool keys or Cold Keys

As the name suggests, it is strongly advised to keep these in a cold environment _i.e._ on a machine permanently disconnected from the internet or other networks.

____
*The pool private cold key governs all pool actions: pool creation, key rotations (cf. KES or VRF key pairs), fee structure, reward/pledge address setting and pool retirement.*
____

----
cardano-cli node key-gen --cold-verification-key-file ./pool.vk --cold-signing-key-file ./pool.sk --operational-certificate-issue-counter-file ./counter
----

Notice that in addition to the `cold-verification-key-file` and `cold-signing-key-file`, we also generated a mandatory `counter` file.

----
{
    "type": "NodeOperationalCertificateIssueCounter",
    "description": "Next certificate issue number: 0",
    "cborHex": "820058203e9dff9346dab83c109a9da73aabf4642ebe64e0274b6a0931ee4b8d838ea304"
}
----

This `counter` will be used to create an `operational certificate` for the stake pool. For now, let's keep in mind that the `operational certificate` is generated by using this `counter` and a KES public key defined in the section "KES keys pair".

We have not yet registered the Cardano stake pool, but we can already know its future on-chain `id` .

----
cardano-cli stake-pool id --cold-verification-key-file ./pool.vk
----

and the answer is

----
pool1xhjzslnkyxvj23almagsmzeck0el7989cqz9rlms8a0pvdly0de
----

==== VRF keys pair

The Verifiable Random Function key pair, or VRF, is used by the node to determine whether or not to attempt to sign a block. A node will check if that is true at every slot.

----
cardano-cli node key-gen-VRF --verification-key-file ./vrf.vk --signing-key-file ./vrf.sk
----

Let's have a look:

----
{
    "type": "VrfVerificationKey_PraosVRF",
    "description": "VRF Verification Key",
    "cborHex": "5820b49718bee9e359b666950c255f2ff7a3ace260963baeb8e8b618d75575dd8ce7"
}
----

The VRF key will reside on the connected block-producing node, as it is used as a parameter to start `cardano-node`.

____
While it is possible to modify the VRF key of a stake pool by sending a new `pool-registration certificate` (more on this later), doing so will forfeit pool rewards for 2 epochs... This should help encourage tight security practices!
____

==== KES keys pair

The Key Evolving Signature signing key, or KES, is the key used by the node to sign a block.

----
cardano-cli node key-gen-KES --verification-key-file ./kes.vk --signing-key-file ./kes.sk
----

Let's have a look:

----
{
    "type": "KesVerificationKey_ed25519_kes_2^6",
    "description": "KES Verification Key",
    "cborHex": "5820f93acee67a1af6529ff02818a18c813d05a71c3cde8a16606133dbbee7f583bc"
}
----

The KES signing key must also reside on the block-producing node.

A `kes.sk` used by a node has a validity range of 93 days (or 62 kes-periods) and needs to be renewed before this period expires. That's  where the `counter` and the `operational certificate` come into play.

==== Operational certificate

Create an `operational certificate`:

----
cardano-cli node issue-op-cert --kes-verification-key-file ./kes.vk --cold-signing-key-file ./pool.sk --operational-certificate-issue-counter-file ./counter --kes-period 694 --out-file opcert
----

*Some explanations are in order:*

* The `counter` will automatically be incremented by exactly *one* after running the above command. Check by yourself:
+
----
{
    "type": "NodeOperationalCertificateIssueCounter",
    "description": "Next certificate issue number: 1",
    "cborHex": "820158203e9dff9346dab83c109a9da73aabf4642ebe64e0274b6a0931ee4b8d838ea304"
}
----

* The `--kes-period` defines the *starting point* of a validity range for the `kes.sk` referenced in the `operational certificate`. One way to calculate the `current-kes-period` of the network on *Cardano mainnet* is to use the formula below. We assume here that `byron_slots`, `byron_end_time` and `slots_per_kes_period` are constant values:
+
----
current-kes-period = (byron_slots+(CurrentTime - byron_end_time))/slots_per_kes_period
current-kes-period = (4492800+(CurrentTime-1596059091))/129600
----
+
`CurrenTime` on your machine can be obtained like this:
+
----
printf '%(%s)T\n' -1
----
+
Some noteworthy Cardano community members have even built fully parameterized ways to calculate the `current-kes-period` for any given network, such as https://github.com/gitmachtl/scripts/blob/master/cardano/mainnet/0x_showCurrentEpochKES.sh[this one]. We cannot thank them enough.

* *You must generate a new KES key pair and a new `operational certificate` before the end of the validity period of exactly 62 kes-periods.* Your block producing node will have to be restarted using the new `kes.sk` and new `operational certificate`. This process is called "KES rotation". *One period corresponds to 1.5 day. That is why KES rotation must be performed at maximum every 93 days.* You can however perform this rotation at an earlier date if more convenient.
+
____
In the example above using `--kes-period 694` , the `operational certificate` will certify that the `kes.sk` is valid until the network reaches the `kes-period 756`.
____

* Since the Babbage era (September 2022), it is important to know that an *`operational certificate` must be rotated using an +1 counter* (previously, it could be any value higher than the last counter) and *only if the pool has produced at least one block during the interval of 93 days.* In case the pool has not produced any blocks during this period of 93 days (or 62 kes-periods), the `counter` must be edited back to its previous value before generating a new `operational-certificate`. An example is shown at the end of this section.
+
`cardano-cli` offers a query that recapitulates all that:
+
----
cardano-cli query kes-period-info --op-cert-file ./opcert --mainnet
----
+
and replies
+
----
✓ Operational certificate's KES period is within the correct KES period interval
✗ No blocks minted so far with the operational certificate at: ./opcert
  On disk operational certificate counter: 0
{
    "qKesCurrentKesPeriod": 695,
    "qKesEndKesInterval": 756,
    "qKesKesKeyExpiry": null,
    "qKesMaxKESEvolutions": 62,
    "qKesNodeStateOperationalCertificateNumber": null,
    "qKesOnDiskOperationalCertificateNumber": 0,
    "qKesRemainingSlotsInKesPeriod": 7891408,
    "qKesSlotsPerKesPeriod": 129600,
    "qKesStartKesInterval": 694
}
----
+
Notice here that by the time we generated our first `operational certificate`, 1 kes-period passed. See the difference between `"qKesCurrentKesPeriod": 695` and `"qKesStartKesInterval": 694` !

*Rotation example with a `counter` reset:*

Let's pretend that 62 kes-periods have passed and the pool has not produced any blocks while using our first `operational certtificate`. It would be then be time to rotate the pool's KES key via a new `operational-certificate`. However, because the pool did not produce any blocks, we must rotate the KES key using a `counter` without the automatic increment performed by the `cardano-cli node issue-op-cert` command.

To revert that automatic increment, we can create a new counter and specify it value using the command below.

----
cardano-cli node new-counter --cold-verification-key-file ./pool.vk --counter-value 0 --operational-certificate-issue-counter-file ./new.counter
----

We set a `--counter-value` of `0` and created the new counter file `new.counter`.

Let's see how `new.counter` looks:

----
{
    "type": "NodeOperationalCertificateIssueCounter",
    "description": "",
    "cborHex": "820058203e9dff9346dab83c109a9da73aabf4642ebe64e0274b6a0931ee4b8d838ea304"
}
----

The `"description"` field has unfortunately been destroyed but what matters is the `cborHex` value, reset to `+"8200...8ea304"+`. Do you notice a difference with the last time we looked at it?

It had a different `cborHex`! `+"8201...8ea304"+`. That little integer change makes all the difference. Make sure to edit manually the `"description"` field of the `new.counter` to avoid getting lost later on.

To finish, this `new.counter` can be used to generate a fresh `operational-certificate`, not forgetting to use a new pair of KES keys and an up-to-date `current-kes-period` of the network. Et voilà.

==== File Summary #2

Your working directory should now contain 16 files:

----
base.addr
counter
kes.sk
kes.vk
new.counter <<< Example file that can safely be destroyed.
opcert
payment.addr
payment.sk
payment.vk
pool.sk
pool.vk
stake.addr
stake.sk
stake.vk
vrf.sk
vrf.vk
----

== Certificates

Certificates are actions performed on the ledger that allow us to:

* Register a stake address (and deregister)
* Register a stake pool (and deregister)
* Delegate an address to a stake pool

[discrete]
==== Address registration (and deregistration)

The stake component contained within a `base.addr` must be registered on the ledger prior being able to delegate ada, receive staking rewards, or use this `base.addr` as way to declare the pool's pledge or receive pool rewards. This is done by sending a registration certificate for the corresponding `stake.addr` on the blockchain.

For the moment, let's construct this registration certificate and we will send it on-chain later:

----
cardano-cli stake-address registration-certificate --stake-verification-key-file ./stake.vk --out-file stake.registration
----

A deregistration certificate for an address can easily be produced using the `cardano-cli stake-address deregistration-certificate`. It is the best way to stop participating in ada staking. To incentivize users, deregistering an address refunds the 2 ada deposit paid for address registration. More on that later.

[discrete]
==== Stake pool registration

Like a `base.addr`, a stake pool will need to make itself known to the network before being able to receive delegation and eventually produce blocks.

This `stake-pool registration-certificate` is a bit complex since it contains an abundance of information relative to pool keys, owner(s), fee structure, pool relays and metadata. Let's observe line by line:

----
cardano-cli stake-pool registration-certificate \
--cold-verification-key-file ./pool.vk \
--vrf-verification-key-file ./vrf.vk \
--pool-reward-account-verification-key-file ./stake.vk \
--pool-cost 340000000 \
--pool-margin 0.02 \
--pool-owner-stake-verification-key-file ./stake.vk \
--pool-pledge 0 \
--pool-relay-ipv4 xxx.xxx.xxx.xxx \
--pool-relay-port xxxx \
--metadata-url url-to-metadata \
--metadata-hash hash-of-metadata \
--mainnet \
--out-file pool.registration
----

`--cold-verification-key-file`: To ensure the right cold secret key signature is present when sending the certificate on-chain.

`--vrf-verification-key-file`: Other pools will check whether the pool had the right to produce a block for a given slot.

`--pool-reward-account-verification-key-file`: The `stake.vk` of the `base.addr` you would like to receive the rewards for running the pool. There can be only one.

____
The reward address will not by required to sign the transaction sending the certificate on-chain.
____

`--pool-cost`: the fixed cost the pool will charge before calculating the margin fee. It cannot be set lower than 340 ada or 340000000 lovelaces at this time on mainnet.

`--pool-margin`: the percentage fee taken by the pool on the remaining rewards after pool cost has been deducted from all block rewards. Its boundaries are 0 (0 %)  and 1 (100%). In this example, it is set at 2%.

`--pool-owner-stake-verification-key-file`: The `stake.vk` of the `base.addr` you would like to use as pledge for the pool. It can be the same as the reward account, but different one may be used. You can have more than one pledge `base.addr`.

____
*The transaction sending the certificate will include a signature for each and every address referenced as a pool owner.*
____

`--pool-pledge`: The lowest amount in lovelace that must be collectively present in the owner(s) account(s), otherwise the pool forfeits all rewards for delegators and itself. Here, to be safe, let's set it to 0.

____
*The address(es) declared as pool's pledge must all be delegated to the pool being registered.*
____

`--pool-relay-ipv4`: The IP address of the relay node used to shield the block produced from connections to the wider network. Note that an `ipv6` option exists.

`--pool-relay-port`: The port on which the relay `cardano-node` will listen to.

NOTE: If more than one relay is used, these parameters can be duplicated like so.

----
--pool-relay-ipv4 IP#1 \
--pool-relay-port xxxx#1\
--pool-relay-ipv4 IP#2 \
--pool-relay-port xxxx#2\
----

Alternatively, the `--single-host-pool-relay` can be used to declare a  stake pool relay's DNS name that corresponds to an A or AAAA DNS record.

----
--single-host-pool-relay dns.record \
--pool-relay-port xxxx \
----

`--metadata-url`: a publicly available URL that serves the metadata of the pool. Below an example of a pool's metadata.json file.

----
{
"name":"Pool's name",
"description":"Example pool",
"ticker":"EXP",
"homepage":"https://examplepool.com"
}
----

`--metadata-hash`: A hash of the accessible metadata.json must be provided to ensure it has not been tempered with. Once the metadata.json file has been downloaded from the url, we can generate a hash with `cardano-cli`:

----
cardano-cli stake-pool metadata-hash --pool-metadata-file ./metadata.json --out-file ./metadata.hash
----

Explore the `cardano-cli stake-pool registration-certificate` command to know more about other options available (`ipv6` or `SRV DNS records` for example).

[discrete]
==== Stake pool deregistration

If you wish to retire a pool, you can easily create a `deregistration certificate`:

----
cardano-cli stake-pool deregistration-certificate --cold-verification-key-file ./pool.vk --epoch 410 --out-file pool.deregistration
----

The  `--epoch`  parameter defines the desired epoch the pool is to become inactive. The epoch must obviously be in the future, but not too far out! No more than 18 months to be precise. This is determinged on Cardano mainnet by a parameter in the `mainnet-shelley-genesis.json` configuration file as the  `eMax`  value. This pool deregistration certificate will have to be sent on-chain and to incentivize pool operators, deregistering a pool refunds the 500 ada deposit paid for pool registration.

____
*Only the pool cold keys are required to retire a pool. The owner has no say in it if they are not the pool operator!*
____

[discrete]
==== Delegation certificate

A `base.addr` can be delegated to a stake pool via a `delegation certificate` like so:

----
cardano-cli stake-address delegation-certificate --stake-verification-key-file ./stake.vk --cold-verification-key-file ./pool.vk --out-file delegation.certificate
----

As expected, you will need the `stake.vk` of the address you wish to delegate, as well as the `pool.vk` of the pool you wish to delegate to. Since the pool is operated by you, this should be no issue!

____
Do not hesitate to explore the `cardano-cli stake-address delegation-certificate` command to find out how one can delegate to another stake pool for which one is not the operator (_i.e._ for which one does not have the corresponding `pool.vk`).
____

[discrete]
==== File Summary #3

Your working directory should now contain 21 files:

----
base.addr
counter
delegation.certificate
kes.sk
kes.vk
new.counter <<< Example file that can safely be destroyed.
metadata.hash
opcert
payment.addr
payment.sk
payment.vk
pool.deregistration <<< Example file that can safely be destroyed.
pool.registration
pool.sk
pool.vk
stake.addr
stake.registration
stake.sk
stake.vk
vrf.sk
vrf.vk
----

Congratulations! We are almost done!

Now that all addresses, keys and certificates are in your hands you will be able to interact on-chain (cf. Section Transactions) and let the world know you are here for serious business.

== Queries

Before building transactions we need to first familiarize ourselves with node queries. We have already encountered one `cardano-cli` query function when looking for the `kes-period-info` of the network.

All query commands can be listed like this:

----
cardano-cli query
----

Rather than diving exhaustively through the entire list, let's focus on some useful queries for the next "Basic transaction" section. Do not hesitate to explore other queries on your own.

[discrete]
==== Protocol parameters

First, let's grab the `protocol-parameters` and copy it in a `pparameter.json` file.

----
cardano-cli query protocol-parameters --mainnet > pparameters.json
----

`pparameter.json` contains a long list of smart contract related costing models as well as useful information to estimate the cost of a transaction. For this we are interested in the latter.

[discrete]
==== UTxOs in an address

In order to manually build the transaction that will post the certificates we created earlier, we first need to know which UTxO to use. An UTxO is uniquely represented on-chain by the combination of a `TxHash` and a `TxIx` (_i.e_ transaction hash and transaction index). An address can hold multiple UTxOs.

We can access the UTxO(s) of an address like so:

----
cardano-cli query utxo --address addr1q9m8pcfxszyvx7gytqc2s9l400aund8z7sazfs2jtfy4h3ft07r3hw6744htxg2gtcd7t28j9tu2s0wlqpmllyj29nwssucyxn --mainnet
----

----
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
0a0043122fb4913b8694bb0b0af7d0c65130d2787ced56bf61bc6ba2fcf5f211     0        5000000 lovelace + TxOutDatumNone
----

For demonstrative purposes, the address generated in the very first section of this tutorial has been funded with 5 ada, or 5000000 lovelaces. This ada amount will *_not_* be enough to carry on with the next steps but it gives you a real world example!

[discrete]
==== Slot height of the network

Transactions in Cardano have an expiry date and the user can define it. To do so, one must first know the `Cardano Time` expressed in `slot` height.

----
cardano-cli query tip --mainnet
----

----
{
    "block": 8668162,
    "epoch": 406,
    "era": "Babbage",
    "hash": "cf5902001ba7024b07c999421804a77b6bf7858c2298e7ead1c5732a6697bcc7",
    "slot": 90368116,
    "syncProgress": "100.00"
}
----

== Basic transaction

Finally, we are getting there! In this section we will create a single transaction that will post the `stake.registration` of the `base.addr`, the `pool.registration` and the `delegation.certificate` that were generated in the previous sections. All in one go.

[discrete]
==== Estimate the transaction fee

We will first create a dummy transaction (`tx.draft`) in order to estimate the transaction fees.

----
cardano-cli transaction build-raw \
--tx-in 0a0043122fb4913b8694bb0b0af7d0c65130d2787ced56bf61bc6ba2fcf5f211#0 \
--tx-out addr1q9m8pcfxszyvx7gytqc2s9l400aund8z7sazfs2jtfy4h3ft07r3hw6744htxg2gtcd7t28j9tu2s0wlqpmllyj29nwssucyxn+0 \
--invalid-hereafter 0 \
--fee 0 \
--certificate-file ./stake.registration \
--certificate-file ./pool.registration \
--certificate-file ./delegation.certificate \
--out-file tx.draft
----

Because it is a `tx.draft` all values are set to `0` .

* `--tx-in`: the UTxO that will be consumed in the format *`TxHash#TxIx`*. Nothing prevents you from consuming more UTxO! Use additional `--tx-in` lines to do so.
* `--tx-out`: the address where ada change will be sent back to. Nothing prevents you from specifying more than one address! Use additional `--tx-out` lines to do so.
* `--invalid-hereafter`: the transaction will be valid until this slot height is reached.
* `--fee`: the transaction fee what we want to calculate!
* `--certificate-file`: adding a certificate to the transaction.

Once we have the `tx.draft`, we can calculate the fees.

----
cardano-cli transaction calculate-min-fee \
--tx-body-file tx.draft  \
--tx-in-count 1 \
--tx-out-count 1 \
--witness-count 3 \
--mainnet \
--protocol-params-file pparameters.json
----

____
You may adjust the `--tx-in-count`, `--tx-out-count`, and `--witness-count` values accordingly. Here, we consume one UTxO, have the change sent back in a single address and will sign the transaction with 3 witnesses (a.k.a. secret keys).
____

The command replies :

----
197313 Lovelace
----

Perfect! Only 0.197313 ada. Not too expensive for a transaction containing three certificates.

____
*Note: Transaction fees are deterministic and as such, have a lower bound. However, one is always allowed to pay more than is required. Please take care with fee inputs.*
____

[discrete]
==== Build the final transaction

----
cardano-cli transaction build-raw \
--tx-in UTxO_TxHash#TxIx \
--tx-out $(cat base.addr)+value \
--invalid-hereafter 90369116 \
--fee 197313 \
--certificate-file ./stake.registration \
--certificate-file ./pool.registration \
--certificate-file ./delegation.certificate \
--out-file tx.final
----

* `--tx-in UTxO_TxHash#TxIx`: `TxHash`#`TxIx` of the UTxO you want to consume!
* `--tx-out $(cat base.addr)+value`
+
[IMPORTANT]
====


*`--tx-out` value is expressed in lovelaces.*
* Registering an address requires a deposit of 2 ada (2000000 lovelaces).
* Registering a pool requires a deposit of 500 ada (500000000 lovelaces).
* This means that the change to the `base.addr` will be : *_value = input - (502 deposit + transaction fee)_*
* Deregistration of an address or a pool will be accounted for by adding 2 ada or 500 ada, respectively, to the ada change value one must calculate to correctly balance a transaction! For example, to degerister simultaneously a base address and a pool: *_value = (input + 502 deposit) - transaction fee_*
====

* `--invalid-hereafter`: The slot tip of the network plus some slots to give your transaction time to get accepted by the network. Here, 1000 slots (seconds on mainnet) or ~ 15 minutes in the future, from the last query we made at `"slot": 90368116`.
* `--fee`: the exact value we calculated earlier.
* `--certificate-file`: adding a certificate to the transaction.
+
____
*Note:*  The order in which the certificates are declared will matter in the final transaction. You cannot delegate to a pool that does not exist yet. You cannot register a pool with an owner's address that is not registered yet. Hence, we register the `base.addr` (its staking part) first, then the pool and finally delegate to it.
____

[discrete]
==== Sign and send a transaction

----
cardano-cli transaction sign \
--tx-body-file ./tx.final  \
--signing-key-file ./payment.skey \
--signing-key-file ./stake.skey \
--signing-key-file ./pool.skey \
--mainnet \
--out-file tx.final.signed
----

The transaction must be signed by three private keys in this case.

* `payment.skey` will authorize spending funds from the `base.addr`.
* `stake.skey` will authorize the use of `base.addr` (its staking part) as a pool owner and authorize delegation to the pool at the same time.
* `pool.skey` will authorize the registration of the pool

____
*The address used to collect pool rewards does not need to sign this transaction. Here, it happens that we use the same address to fulfill the reward and the pledge functions. The pool owner (pledge) does not need to sign a `de-registration certificate`. Updating the pool parameters consists in sending a new `pool-registration` certificate. Deposit for the pool only occurs during the first registration.* 
____

----
cardano-cli transaction submit \
--tx-file tx.final.signed \
--mainnet
----

Congratulations ! It is all done, the pool is now registered! With some delegated stake, it will sign blocks and pay rewards to the `base.addr` (after the block producing node is started with the appropriate keys of course).

==== 	Rewards withdrawal

Eventually, with enough saturation, the pool will mint blocks and start accumulating some ada rewards. However, these ada are in the stake account associated to the `base.addr` and as such cannot be spent as UTxOs.

Let's query a random address that accumulated ada rewards:

----
cardano-cli query stake-address-info --address stake1u97v0sjx96u5lydjfe2g5qdwkj6plm87h80q5vc0ma6wjpq22mh4c --mainnet
----

----
[
    {
        "address": "stake1u97v0sjx96u5lydjfe2g5qdwkj6plm87h80q5vc0ma6wjpq22mh4c",
        "delegation": "pool1kchver88u3kygsak8wgll7htr8uxn5v35lfrsyy842nkscrzyvj",
        "rewardAccountBalance": 370751053
    }
]
----

This one contains `370751053` lovelaces or  `370.751053 ada` rewards.

A withdrawal transaction can be made to transform these ada rewards into spendable UTxO.

Again, let's estimate first the transaction fee for this:

----
cardano-cli transaction build-raw \
--tx-in 0a0043122fb4913b8694bb0b0af7d0c65130d2787ced56bf61bc6ba2fcf5f211#0 \
--tx-out $(cat base.addr)+0 \
--withdrawal $(cat stake.addr)+0 \
--invalid-hereafter 0 \
--fee 0 \
--out-file withdraw.draft
----

`--withdrawal`: specifies from which `stake.addr` rewards will be withdrawn from; `+` separates the address from the value withdrawn in lovelace.

____
Since we only create a fake transaction in order to calculate transaction fees, we set the value withdrawn at 0.
____

Next:

----
cardano-cli transaction calculate-min-fee \
--tx-body-file withdraw.draft  \
--tx-in-count 1 \
--tx-out-count 1 \
--witness-count 2 \
--mainnet \
--protocol-params-file pparameters.json
----

----
178525 Lovelace
----

Almost done. Let's craft the real withdrawal transaction now.

----
cardano-cli transaction build-raw \
--tx-in 0a0043122fb4913b8694bb0b0af7d0c65130d2787ced56bf61bc6ba2fcf5f211#0 \
--tx-out $(cat base.addr)+375572528 \
--withdrawal $(cat stake.addr)+370751053 \
--invalid-hereafter 90455278 \
--fee 178525 \
--out-file withdraw.draft
----

[IMPORTANT]
====


*All values are expressed in lovelaces.*

* The `base.addr` will receive as change : *`UTxO_value + rewards_withdrawn - transaction_fees`*
* *Rewards are withdrawn in full. Partial withdrawals are not allowed.*
* Nothing prevents the addition of extra `--tx-out` fields, as long as the transaction is balanced correctly (total input - transaction fees = total output).
====

We can now sign the transaction:

----
cardano-cli transaction sign \
--tx-body-file ./withdraw.draft  \
--signing-key-file ./payment.skey \
--signing-key-file ./stake.skey \
--mainnet \
--out-file withdraw.signed
----

Two witnesses are required:

* The `payment.sk` of the `base.addr` that pays for the transaction fee.
* The `stake.sk` of the stake.addr, to allow the withdrawal of ada rewards.

The transaction can now be sent

----
cardano-cli transaction submit \
--tx-file tx.final.signed \
--mainnet
----

== Epilogue

This guide to create a stake pool describes all `cardano-cli` actions required become an *_autonomous Stake Pool Operator_* on Cardano. Let's hope this longer-than-desired document helped shed some light on the many moving parts involved.

____
Community tooling exists today that abstracts most of the steps presented, such as the https://github.com/cardano-community/guild-operators[Guild-Operators] or the https://github.com/gitmachtl/scripts[Stake Pool Operators Scripts] repositories.

In addition, many operations that need a running instance of `cardano-node` (to query or post on the ledger) can be performed using a copycat of `cardano-cli` called https://github.com/blockfrost/blockfrost-cardano-cli[`blockfrost-cardano-cli`]. It can be sometimes faster than querying your local `cardano-node` instance!

Because handling private keys is not a small feat, it is recommended to utilize tools that use hardware wallets. One that comes to mind is `cardano-hw-cli`, a version of `cardano-cli` that leverages hardware wallets to manage both addresses and pool private keys. You can find it https://github.com/vacuumlabs/cardano-hw-cli[here].

*_Please note that such tools should not be used without a clear overview and hands-on experience of how things work. And please, do yourself a huge favor: practice on testnets if it's your first time!_*
____
